// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

var (
	v1HighlightsCollectionGetResponseFieldData = big.NewInt(1 << 0)
)

type V1HighlightsCollectionGetResponse struct {
	Data []*V1HighlightsCollectionGetResponseDataItem `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1HighlightsCollectionGetResponse) GetData() []*V1HighlightsCollectionGetResponseDataItem {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V1HighlightsCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1HighlightsCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetResponse) SetData(data []*V1HighlightsCollectionGetResponseDataItem) {
	v.Data = data
	v.require(v1HighlightsCollectionGetResponseFieldData)
}

func (v *V1HighlightsCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1HighlightsCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1HighlightsCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1HighlightsCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1HighlightsCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1HighlightsCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1HighlightsCollectionGetResponseDataItemFieldBibleID   = big.NewInt(1 << 0)
	v1HighlightsCollectionGetResponseDataItemFieldPassageID = big.NewInt(1 << 1)
	v1HighlightsCollectionGetResponseDataItemFieldColor     = big.NewInt(1 << 2)
)

type V1HighlightsCollectionGetResponseDataItem struct {
	// Bible version identifier
	BibleID int `json:"bible_id" url:"bible_id"`
	// The passage identifier (verse USFM format)
	PassageID string `json:"passage_id" url:"passage_id"`
	// The highlight color in hex format
	Color string `json:"color" url:"color"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1HighlightsCollectionGetResponseDataItem) GetBibleID() int {
	if v == nil {
		return 0
	}
	return v.BibleID
}

func (v *V1HighlightsCollectionGetResponseDataItem) GetPassageID() string {
	if v == nil {
		return ""
	}
	return v.PassageID
}

func (v *V1HighlightsCollectionGetResponseDataItem) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}

func (v *V1HighlightsCollectionGetResponseDataItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1HighlightsCollectionGetResponseDataItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetResponseDataItem) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1HighlightsCollectionGetResponseDataItemFieldBibleID)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetResponseDataItem) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1HighlightsCollectionGetResponseDataItemFieldPassageID)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetResponseDataItem) SetColor(color string) {
	v.Color = color
	v.require(v1HighlightsCollectionGetResponseDataItemFieldColor)
}

func (v *V1HighlightsCollectionGetResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1HighlightsCollectionGetResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1HighlightsCollectionGetResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1HighlightsCollectionGetResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed V1HighlightsCollectionGetResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1HighlightsCollectionGetResponseDataItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1HighlightsCollectionPostRequestHighlightFieldBibleID   = big.NewInt(1 << 0)
	v1HighlightsCollectionPostRequestHighlightFieldPassageID = big.NewInt(1 << 1)
	v1HighlightsCollectionPostRequestHighlightFieldColor     = big.NewInt(1 << 2)
)

type V1HighlightsCollectionPostRequestHighlight struct {
	// Bible version identifier
	BibleID int `json:"bible_id" url:"bible_id"`
	// The passage identifier (verse USFM format)
	PassageID string `json:"passage_id" url:"passage_id"`
	// The highlight color in hex format
	Color string `json:"color" url:"color"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1HighlightsCollectionPostRequestHighlight) GetBibleID() int {
	if v == nil {
		return 0
	}
	return v.BibleID
}

func (v *V1HighlightsCollectionPostRequestHighlight) GetPassageID() string {
	if v == nil {
		return ""
	}
	return v.PassageID
}

func (v *V1HighlightsCollectionPostRequestHighlight) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}

func (v *V1HighlightsCollectionPostRequestHighlight) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1HighlightsCollectionPostRequestHighlight) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostRequestHighlight) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1HighlightsCollectionPostRequestHighlightFieldBibleID)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostRequestHighlight) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1HighlightsCollectionPostRequestHighlightFieldPassageID)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostRequestHighlight) SetColor(color string) {
	v.Color = color
	v.require(v1HighlightsCollectionPostRequestHighlightFieldColor)
}

func (v *V1HighlightsCollectionPostRequestHighlight) UnmarshalJSON(data []byte) error {
	type unmarshaler V1HighlightsCollectionPostRequestHighlight
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1HighlightsCollectionPostRequestHighlight(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1HighlightsCollectionPostRequestHighlight) MarshalJSON() ([]byte, error) {
	type embed V1HighlightsCollectionPostRequestHighlight
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1HighlightsCollectionPostRequestHighlight) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1HighlightsCollectionPostResponseFieldBibleID   = big.NewInt(1 << 0)
	v1HighlightsCollectionPostResponseFieldPassageID = big.NewInt(1 << 1)
	v1HighlightsCollectionPostResponseFieldColor     = big.NewInt(1 << 2)
)

type V1HighlightsCollectionPostResponse struct {
	// Bible version identifier
	BibleID int `json:"bible_id" url:"bible_id"`
	// The passage identifier (verse USFM format)
	PassageID string `json:"passage_id" url:"passage_id"`
	// The highlight color in hex format
	Color string `json:"color" url:"color"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1HighlightsCollectionPostResponse) GetBibleID() int {
	if v == nil {
		return 0
	}
	return v.BibleID
}

func (v *V1HighlightsCollectionPostResponse) GetPassageID() string {
	if v == nil {
		return ""
	}
	return v.PassageID
}

func (v *V1HighlightsCollectionPostResponse) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}

func (v *V1HighlightsCollectionPostResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1HighlightsCollectionPostResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostResponse) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1HighlightsCollectionPostResponseFieldBibleID)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostResponse) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1HighlightsCollectionPostResponseFieldPassageID)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostResponse) SetColor(color string) {
	v.Color = color
	v.require(v1HighlightsCollectionPostResponseFieldColor)
}

func (v *V1HighlightsCollectionPostResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1HighlightsCollectionPostResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1HighlightsCollectionPostResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1HighlightsCollectionPostResponse) MarshalJSON() ([]byte, error) {
	type embed V1HighlightsCollectionPostResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1HighlightsCollectionPostResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1HighlightsCollectionGetRequestFieldBibleID   = big.NewInt(1 << 0)
	v1HighlightsCollectionGetRequestFieldPassageID = big.NewInt(1 << 1)
)

type V1HighlightsCollectionGetRequest struct {
	// The Bible version identifier
	BibleID int `json:"-" url:"bible_id"`
	// The passage identifier (verse or chapter USFM format)
	PassageID string `json:"-" url:"passage_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1HighlightsCollectionGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetRequest) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1HighlightsCollectionGetRequestFieldBibleID)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionGetRequest) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1HighlightsCollectionGetRequestFieldPassageID)
}

var (
	v1HighlightsCollectionPostRequestFieldRequestID = big.NewInt(1 << 0)
	v1HighlightsCollectionPostRequestFieldHighlight = big.NewInt(1 << 1)
)

type V1HighlightsCollectionPostRequest struct {
	// Request UUID for idempotent create retries.
	RequestID string                                      `json:"request_id" url:"-"`
	Highlight *V1HighlightsCollectionPostRequestHighlight `json:"highlight" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1HighlightsCollectionPostRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostRequest) SetRequestID(requestID string) {
	v.RequestID = requestID
	v.require(v1HighlightsCollectionPostRequestFieldRequestID)
}

// SetHighlight sets the Highlight field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsCollectionPostRequest) SetHighlight(highlight *V1HighlightsCollectionPostRequestHighlight) {
	v.Highlight = highlight
	v.require(v1HighlightsCollectionPostRequestFieldHighlight)
}

func (v *V1HighlightsCollectionPostRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler V1HighlightsCollectionPostRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = V1HighlightsCollectionPostRequest(body)
	return nil
}

func (v *V1HighlightsCollectionPostRequest) MarshalJSON() ([]byte, error) {
	type embed V1HighlightsCollectionPostRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	v1HighlightsResourceDeleteRequestFieldPassageIDPath = big.NewInt(1 << 0)
	v1HighlightsResourceDeleteRequestFieldBibleID       = big.NewInt(1 << 1)
)

type V1HighlightsResourceDeleteRequest struct {
	// The passage identifier (verse or chapter USFM format)
	PassageIDPath string `json:"-" url:"-"`
	// The Bible version identifier
	BibleID int `json:"-" url:"bible_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1HighlightsResourceDeleteRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPassageIDPath sets the PassageIDPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsResourceDeleteRequest) SetPassageIDPath(passageIDPath string) {
	v.PassageIDPath = passageIDPath
	v.require(v1HighlightsResourceDeleteRequestFieldPassageIDPath)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1HighlightsResourceDeleteRequest) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1HighlightsResourceDeleteRequestFieldBibleID)
}
