// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

type V1LanguagesCollectionGetRequestPageSize string

const (
	V1LanguagesCollectionGetRequestPageSizeAll V1LanguagesCollectionGetRequestPageSize = "*"
)

func NewV1LanguagesCollectionGetRequestPageSizeFromString(s string) (V1LanguagesCollectionGetRequestPageSize, error) {
	switch s {
	case "*":
		return V1LanguagesCollectionGetRequestPageSizeAll, nil
	}
	var t V1LanguagesCollectionGetRequestPageSize
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v V1LanguagesCollectionGetRequestPageSize) Ptr() *V1LanguagesCollectionGetRequestPageSize {
	return &v
}

var (
	v1LanguagesCollectionGetResponseFieldData          = big.NewInt(1 << 0)
	v1LanguagesCollectionGetResponseFieldNextPageToken = big.NewInt(1 << 1)
	v1LanguagesCollectionGetResponseFieldTotalSize     = big.NewInt(1 << 2)
)

type V1LanguagesCollectionGetResponse struct {
	Data []*V1LanguagesCollectionGetResponseDataItem `json:"data,omitempty" url:"data,omitempty"`
	// Token to send to server when retrieving the next page of results.
	NextPageToken *string `json:"next_page_token,omitempty" url:"next_page_token,omitempty"`
	// Total number of languages in collection matching parameters.
	TotalSize *int `json:"total_size,omitempty" url:"total_size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1LanguagesCollectionGetResponse) GetData() []*V1LanguagesCollectionGetResponseDataItem {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V1LanguagesCollectionGetResponse) GetNextPageToken() *string {
	if v == nil {
		return nil
	}
	return v.NextPageToken
}

func (v *V1LanguagesCollectionGetResponse) GetTotalSize() *int {
	if v == nil {
		return nil
	}
	return v.TotalSize
}

func (v *V1LanguagesCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1LanguagesCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponse) SetData(data []*V1LanguagesCollectionGetResponseDataItem) {
	v.Data = data
	v.require(v1LanguagesCollectionGetResponseFieldData)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponse) SetNextPageToken(nextPageToken *string) {
	v.NextPageToken = nextPageToken
	v.require(v1LanguagesCollectionGetResponseFieldNextPageToken)
}

// SetTotalSize sets the TotalSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponse) SetTotalSize(totalSize *int) {
	v.TotalSize = totalSize
	v.require(v1LanguagesCollectionGetResponseFieldTotalSize)
}

func (v *V1LanguagesCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1LanguagesCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1LanguagesCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1LanguagesCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1LanguagesCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1LanguagesCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Region-agnostic language resource keyed by canonical BCP 47 language or language+script. Variants and a simple extensions indicator are included for completeness, but regions are excluded except for a small, enumerated set of region variants that speakers treat as distinct languages (for example pt-PT vs pt-BR, es-ES vs es-419); full extension data is always excluded.
var (
	v1LanguagesCollectionGetResponseDataItemFieldID                 = big.NewInt(1 << 0)
	v1LanguagesCollectionGetResponseDataItemFieldLanguage           = big.NewInt(1 << 1)
	v1LanguagesCollectionGetResponseDataItemFieldScript             = big.NewInt(1 << 2)
	v1LanguagesCollectionGetResponseDataItemFieldScriptName         = big.NewInt(1 << 3)
	v1LanguagesCollectionGetResponseDataItemFieldAliases            = big.NewInt(1 << 4)
	v1LanguagesCollectionGetResponseDataItemFieldDisplayNames       = big.NewInt(1 << 5)
	v1LanguagesCollectionGetResponseDataItemFieldLocalizedName      = big.NewInt(1 << 6)
	v1LanguagesCollectionGetResponseDataItemFieldScripts            = big.NewInt(1 << 7)
	v1LanguagesCollectionGetResponseDataItemFieldVariants           = big.NewInt(1 << 8)
	v1LanguagesCollectionGetResponseDataItemFieldCountries          = big.NewInt(1 << 9)
	v1LanguagesCollectionGetResponseDataItemFieldTextDirection      = big.NewInt(1 << 10)
	v1LanguagesCollectionGetResponseDataItemFieldWritingPopulation  = big.NewInt(1 << 11)
	v1LanguagesCollectionGetResponseDataItemFieldSpeakingPopulation = big.NewInt(1 << 12)
	v1LanguagesCollectionGetResponseDataItemFieldDefaultBibleID     = big.NewInt(1 << 13)
)

type V1LanguagesCollectionGetResponseDataItem struct {
	// Canonical BCP 47 id limited to language, language+script, or one of the enumerated region-significant variants (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Other regions, variants, and extensions are not allowed.
	ID string `json:"id" url:"id"`
	// ISO 639 canonical language subtag
	Language string `json:"language" url:"language"`
	// ISO 15924 script code if present in id
	Script *string `json:"script,omitempty" url:"script,omitempty"`
	// The English name for the script
	ScriptName *string `json:"script_name,omitempty" url:"script_name,omitempty"`
	// Deprecated or legacy subtags mapped during canonicalization for this language.
	Aliases []string `json:"aliases,omitempty" url:"aliases,omitempty"`
	// A map of every known display name for this language, keyed by the locale the name is written in. Covers all locales the platform can render (e.g. the English, endonym, and hundreds of other localized names), so this object is large; request fields[] without display_names to omit it when you only need localized_name.
	DisplayNames *V1LanguagesCollectionGetResponseDataItemDisplayNames `json:"display_names,omitempty" url:"display_names,omitempty"`
	// The single display name chosen from display_names for the request's Accept-Language header. Selection is per language and uses the Accept-Language priority list, then falls back to the English name, then the first available name. The Content-Language response header reports the locale negotiated for the response as a whole; in a collection an individual language may fall back to a different locale than that header when it has no name in the negotiated one. Use this when you want one name to show the user; use display_names when you need the full set.
	LocalizedName *string `json:"localized_name,omitempty" url:"localized_name,omitempty"`
	// All scripts known for this language (CLDR/ISO-15924)
	Scripts []string `json:"scripts,omitempty" url:"scripts,omitempty"`
	// Variants associated with this language (not part of the id)
	Variants []string `json:"variants,omitempty" url:"variants,omitempty"`
	// Ids of countries where this language is used or supported. Extended details can be retrieved from the countries API with the provided id.
	Countries []string `json:"countries,omitempty" url:"countries,omitempty"`
	// Default text direction for this language. ltr is left to right and rtl is right to left.
	TextDirection *V1LanguagesCollectionGetResponseDataItemTextDirection `json:"text_direction,omitempty" url:"text_direction,omitempty"`
	// Estimated number of souls that write in this language.
	WritingPopulation *int `json:"writing_population,omitempty" url:"writing_population,omitempty"`
	// Estimated number of souls that speak in this language.
	SpeakingPopulation *int `json:"speaking_population,omitempty" url:"speaking_population,omitempty"`
	// The chosen default Bible version for this language.
	DefaultBibleID *int `json:"default_bible_id,omitempty" url:"default_bible_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetLanguage() string {
	if v == nil {
		return ""
	}
	return v.Language
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetScript() *string {
	if v == nil {
		return nil
	}
	return v.Script
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetScriptName() *string {
	if v == nil {
		return nil
	}
	return v.ScriptName
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetAliases() []string {
	if v == nil {
		return nil
	}
	return v.Aliases
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetDisplayNames() *V1LanguagesCollectionGetResponseDataItemDisplayNames {
	if v == nil {
		return nil
	}
	return v.DisplayNames
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetLocalizedName() *string {
	if v == nil {
		return nil
	}
	return v.LocalizedName
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetScripts() []string {
	if v == nil {
		return nil
	}
	return v.Scripts
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetVariants() []string {
	if v == nil {
		return nil
	}
	return v.Variants
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetCountries() []string {
	if v == nil {
		return nil
	}
	return v.Countries
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetTextDirection() *V1LanguagesCollectionGetResponseDataItemTextDirection {
	if v == nil {
		return nil
	}
	return v.TextDirection
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetWritingPopulation() *int {
	if v == nil {
		return nil
	}
	return v.WritingPopulation
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetSpeakingPopulation() *int {
	if v == nil {
		return nil
	}
	return v.SpeakingPopulation
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetDefaultBibleID() *int {
	if v == nil {
		return nil
	}
	return v.DefaultBibleID
}

func (v *V1LanguagesCollectionGetResponseDataItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1LanguagesCollectionGetResponseDataItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetID(id string) {
	v.ID = id
	v.require(v1LanguagesCollectionGetResponseDataItemFieldID)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetLanguage(language string) {
	v.Language = language
	v.require(v1LanguagesCollectionGetResponseDataItemFieldLanguage)
}

// SetScript sets the Script field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetScript(script *string) {
	v.Script = script
	v.require(v1LanguagesCollectionGetResponseDataItemFieldScript)
}

// SetScriptName sets the ScriptName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetScriptName(scriptName *string) {
	v.ScriptName = scriptName
	v.require(v1LanguagesCollectionGetResponseDataItemFieldScriptName)
}

// SetAliases sets the Aliases field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetAliases(aliases []string) {
	v.Aliases = aliases
	v.require(v1LanguagesCollectionGetResponseDataItemFieldAliases)
}

// SetDisplayNames sets the DisplayNames field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetDisplayNames(displayNames *V1LanguagesCollectionGetResponseDataItemDisplayNames) {
	v.DisplayNames = displayNames
	v.require(v1LanguagesCollectionGetResponseDataItemFieldDisplayNames)
}

// SetLocalizedName sets the LocalizedName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetLocalizedName(localizedName *string) {
	v.LocalizedName = localizedName
	v.require(v1LanguagesCollectionGetResponseDataItemFieldLocalizedName)
}

// SetScripts sets the Scripts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetScripts(scripts []string) {
	v.Scripts = scripts
	v.require(v1LanguagesCollectionGetResponseDataItemFieldScripts)
}

// SetVariants sets the Variants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetVariants(variants []string) {
	v.Variants = variants
	v.require(v1LanguagesCollectionGetResponseDataItemFieldVariants)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetCountries(countries []string) {
	v.Countries = countries
	v.require(v1LanguagesCollectionGetResponseDataItemFieldCountries)
}

// SetTextDirection sets the TextDirection field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetTextDirection(textDirection *V1LanguagesCollectionGetResponseDataItemTextDirection) {
	v.TextDirection = textDirection
	v.require(v1LanguagesCollectionGetResponseDataItemFieldTextDirection)
}

// SetWritingPopulation sets the WritingPopulation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetWritingPopulation(writingPopulation *int) {
	v.WritingPopulation = writingPopulation
	v.require(v1LanguagesCollectionGetResponseDataItemFieldWritingPopulation)
}

// SetSpeakingPopulation sets the SpeakingPopulation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetSpeakingPopulation(speakingPopulation *int) {
	v.SpeakingPopulation = speakingPopulation
	v.require(v1LanguagesCollectionGetResponseDataItemFieldSpeakingPopulation)
}

// SetDefaultBibleID sets the DefaultBibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItem) SetDefaultBibleID(defaultBibleID *int) {
	v.DefaultBibleID = defaultBibleID
	v.require(v1LanguagesCollectionGetResponseDataItemFieldDefaultBibleID)
}

func (v *V1LanguagesCollectionGetResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1LanguagesCollectionGetResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1LanguagesCollectionGetResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1LanguagesCollectionGetResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed V1LanguagesCollectionGetResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1LanguagesCollectionGetResponseDataItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// A map of every known display name for this language, keyed by the locale the name is written in. Covers all locales the platform can render (e.g. the English, endonym, and hundreds of other localized names), so this object is large; request fields[] without display_names to omit it when you only need localized_name.
var (
	v1LanguagesCollectionGetResponseDataItemDisplayNamesFieldEn = big.NewInt(1 << 0)
)

type V1LanguagesCollectionGetResponseDataItemDisplayNames struct {
	En *string `json:"en,omitempty" url:"en,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) GetEn() *string {
	if v == nil {
		return nil
	}
	return v.En
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetEn sets the En field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) SetEn(en *string) {
	v.En = en
	v.require(v1LanguagesCollectionGetResponseDataItemDisplayNamesFieldEn)
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) UnmarshalJSON(data []byte) error {
	type unmarshaler V1LanguagesCollectionGetResponseDataItemDisplayNames
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1LanguagesCollectionGetResponseDataItemDisplayNames(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) MarshalJSON() ([]byte, error) {
	type embed V1LanguagesCollectionGetResponseDataItemDisplayNames
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1LanguagesCollectionGetResponseDataItemDisplayNames) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Default text direction for this language. ltr is left to right and rtl is right to left.
type V1LanguagesCollectionGetResponseDataItemTextDirection string

const (
	V1LanguagesCollectionGetResponseDataItemTextDirectionLtr V1LanguagesCollectionGetResponseDataItemTextDirection = "ltr"
	V1LanguagesCollectionGetResponseDataItemTextDirectionRtl V1LanguagesCollectionGetResponseDataItemTextDirection = "rtl"
)

func NewV1LanguagesCollectionGetResponseDataItemTextDirectionFromString(s string) (V1LanguagesCollectionGetResponseDataItemTextDirection, error) {
	switch s {
	case "ltr":
		return V1LanguagesCollectionGetResponseDataItemTextDirectionLtr, nil
	case "rtl":
		return V1LanguagesCollectionGetResponseDataItemTextDirectionRtl, nil
	}
	var t V1LanguagesCollectionGetResponseDataItemTextDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v V1LanguagesCollectionGetResponseDataItemTextDirection) Ptr() *V1LanguagesCollectionGetResponseDataItemTextDirection {
	return &v
}

// Region-agnostic language resource keyed by canonical BCP 47 language or language+script. Variants and a simple extensions indicator are included for completeness, but regions are excluded except for a small, enumerated set of region variants that speakers treat as distinct languages (for example pt-PT vs pt-BR, es-ES vs es-419); full extension data is always excluded.
var (
	v1LanguagesResourceGetResponseFieldID                 = big.NewInt(1 << 0)
	v1LanguagesResourceGetResponseFieldLanguage           = big.NewInt(1 << 1)
	v1LanguagesResourceGetResponseFieldScript             = big.NewInt(1 << 2)
	v1LanguagesResourceGetResponseFieldScriptName         = big.NewInt(1 << 3)
	v1LanguagesResourceGetResponseFieldAliases            = big.NewInt(1 << 4)
	v1LanguagesResourceGetResponseFieldDisplayNames       = big.NewInt(1 << 5)
	v1LanguagesResourceGetResponseFieldLocalizedName      = big.NewInt(1 << 6)
	v1LanguagesResourceGetResponseFieldScripts            = big.NewInt(1 << 7)
	v1LanguagesResourceGetResponseFieldVariants           = big.NewInt(1 << 8)
	v1LanguagesResourceGetResponseFieldCountries          = big.NewInt(1 << 9)
	v1LanguagesResourceGetResponseFieldTextDirection      = big.NewInt(1 << 10)
	v1LanguagesResourceGetResponseFieldWritingPopulation  = big.NewInt(1 << 11)
	v1LanguagesResourceGetResponseFieldSpeakingPopulation = big.NewInt(1 << 12)
	v1LanguagesResourceGetResponseFieldDefaultBibleID     = big.NewInt(1 << 13)
)

type V1LanguagesResourceGetResponse struct {
	// Canonical BCP 47 id limited to language, language+script, or one of the enumerated region-significant variants (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Other regions, variants, and extensions are not allowed.
	ID string `json:"id" url:"id"`
	// ISO 639 canonical language subtag
	Language string `json:"language" url:"language"`
	// ISO 15924 script code if present in id
	Script *string `json:"script,omitempty" url:"script,omitempty"`
	// The English name for the script
	ScriptName *string `json:"script_name,omitempty" url:"script_name,omitempty"`
	// Deprecated or legacy subtags mapped during canonicalization for this language.
	Aliases []string `json:"aliases,omitempty" url:"aliases,omitempty"`
	// A map of every known display name for this language, keyed by the locale the name is written in. Covers all locales the platform can render (e.g. the English, endonym, and hundreds of other localized names), so this object is large; request fields[] without display_names to omit it when you only need localized_name.
	DisplayNames *V1LanguagesResourceGetResponseDisplayNames `json:"display_names,omitempty" url:"display_names,omitempty"`
	// The single display name chosen from display_names for the request's Accept-Language header. Selection is per language and uses the Accept-Language priority list, then falls back to the English name, then the first available name. The Content-Language response header reports the locale negotiated for the response as a whole; in a collection an individual language may fall back to a different locale than that header when it has no name in the negotiated one. Use this when you want one name to show the user; use display_names when you need the full set.
	LocalizedName *string `json:"localized_name,omitempty" url:"localized_name,omitempty"`
	// All scripts known for this language (CLDR/ISO-15924)
	Scripts []string `json:"scripts,omitempty" url:"scripts,omitempty"`
	// Variants associated with this language (not part of the id)
	Variants []string `json:"variants,omitempty" url:"variants,omitempty"`
	// Ids of countries where this language is used or supported. Extended details can be retrieved from the countries API with the provided id.
	Countries []string `json:"countries,omitempty" url:"countries,omitempty"`
	// Default text direction for this language. ltr is left to right and rtl is right to left.
	TextDirection *V1LanguagesResourceGetResponseTextDirection `json:"text_direction,omitempty" url:"text_direction,omitempty"`
	// Estimated number of souls that write in this language.
	WritingPopulation *int `json:"writing_population,omitempty" url:"writing_population,omitempty"`
	// Estimated number of souls that speak in this language.
	SpeakingPopulation *int `json:"speaking_population,omitempty" url:"speaking_population,omitempty"`
	// The chosen default Bible version for this language.
	DefaultBibleID *int `json:"default_bible_id,omitempty" url:"default_bible_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1LanguagesResourceGetResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V1LanguagesResourceGetResponse) GetLanguage() string {
	if v == nil {
		return ""
	}
	return v.Language
}

func (v *V1LanguagesResourceGetResponse) GetScript() *string {
	if v == nil {
		return nil
	}
	return v.Script
}

func (v *V1LanguagesResourceGetResponse) GetScriptName() *string {
	if v == nil {
		return nil
	}
	return v.ScriptName
}

func (v *V1LanguagesResourceGetResponse) GetAliases() []string {
	if v == nil {
		return nil
	}
	return v.Aliases
}

func (v *V1LanguagesResourceGetResponse) GetDisplayNames() *V1LanguagesResourceGetResponseDisplayNames {
	if v == nil {
		return nil
	}
	return v.DisplayNames
}

func (v *V1LanguagesResourceGetResponse) GetLocalizedName() *string {
	if v == nil {
		return nil
	}
	return v.LocalizedName
}

func (v *V1LanguagesResourceGetResponse) GetScripts() []string {
	if v == nil {
		return nil
	}
	return v.Scripts
}

func (v *V1LanguagesResourceGetResponse) GetVariants() []string {
	if v == nil {
		return nil
	}
	return v.Variants
}

func (v *V1LanguagesResourceGetResponse) GetCountries() []string {
	if v == nil {
		return nil
	}
	return v.Countries
}

func (v *V1LanguagesResourceGetResponse) GetTextDirection() *V1LanguagesResourceGetResponseTextDirection {
	if v == nil {
		return nil
	}
	return v.TextDirection
}

func (v *V1LanguagesResourceGetResponse) GetWritingPopulation() *int {
	if v == nil {
		return nil
	}
	return v.WritingPopulation
}

func (v *V1LanguagesResourceGetResponse) GetSpeakingPopulation() *int {
	if v == nil {
		return nil
	}
	return v.SpeakingPopulation
}

func (v *V1LanguagesResourceGetResponse) GetDefaultBibleID() *int {
	if v == nil {
		return nil
	}
	return v.DefaultBibleID
}

func (v *V1LanguagesResourceGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1LanguagesResourceGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetID(id string) {
	v.ID = id
	v.require(v1LanguagesResourceGetResponseFieldID)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetLanguage(language string) {
	v.Language = language
	v.require(v1LanguagesResourceGetResponseFieldLanguage)
}

// SetScript sets the Script field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetScript(script *string) {
	v.Script = script
	v.require(v1LanguagesResourceGetResponseFieldScript)
}

// SetScriptName sets the ScriptName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetScriptName(scriptName *string) {
	v.ScriptName = scriptName
	v.require(v1LanguagesResourceGetResponseFieldScriptName)
}

// SetAliases sets the Aliases field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetAliases(aliases []string) {
	v.Aliases = aliases
	v.require(v1LanguagesResourceGetResponseFieldAliases)
}

// SetDisplayNames sets the DisplayNames field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetDisplayNames(displayNames *V1LanguagesResourceGetResponseDisplayNames) {
	v.DisplayNames = displayNames
	v.require(v1LanguagesResourceGetResponseFieldDisplayNames)
}

// SetLocalizedName sets the LocalizedName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetLocalizedName(localizedName *string) {
	v.LocalizedName = localizedName
	v.require(v1LanguagesResourceGetResponseFieldLocalizedName)
}

// SetScripts sets the Scripts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetScripts(scripts []string) {
	v.Scripts = scripts
	v.require(v1LanguagesResourceGetResponseFieldScripts)
}

// SetVariants sets the Variants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetVariants(variants []string) {
	v.Variants = variants
	v.require(v1LanguagesResourceGetResponseFieldVariants)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetCountries(countries []string) {
	v.Countries = countries
	v.require(v1LanguagesResourceGetResponseFieldCountries)
}

// SetTextDirection sets the TextDirection field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetTextDirection(textDirection *V1LanguagesResourceGetResponseTextDirection) {
	v.TextDirection = textDirection
	v.require(v1LanguagesResourceGetResponseFieldTextDirection)
}

// SetWritingPopulation sets the WritingPopulation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetWritingPopulation(writingPopulation *int) {
	v.WritingPopulation = writingPopulation
	v.require(v1LanguagesResourceGetResponseFieldWritingPopulation)
}

// SetSpeakingPopulation sets the SpeakingPopulation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetSpeakingPopulation(speakingPopulation *int) {
	v.SpeakingPopulation = speakingPopulation
	v.require(v1LanguagesResourceGetResponseFieldSpeakingPopulation)
}

// SetDefaultBibleID sets the DefaultBibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponse) SetDefaultBibleID(defaultBibleID *int) {
	v.DefaultBibleID = defaultBibleID
	v.require(v1LanguagesResourceGetResponseFieldDefaultBibleID)
}

func (v *V1LanguagesResourceGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1LanguagesResourceGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1LanguagesResourceGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1LanguagesResourceGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1LanguagesResourceGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1LanguagesResourceGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// A map of every known display name for this language, keyed by the locale the name is written in. Covers all locales the platform can render (e.g. the English, endonym, and hundreds of other localized names), so this object is large; request fields[] without display_names to omit it when you only need localized_name.
var (
	v1LanguagesResourceGetResponseDisplayNamesFieldEn = big.NewInt(1 << 0)
)

type V1LanguagesResourceGetResponseDisplayNames struct {
	En *string `json:"en,omitempty" url:"en,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1LanguagesResourceGetResponseDisplayNames) GetEn() *string {
	if v == nil {
		return nil
	}
	return v.En
}

func (v *V1LanguagesResourceGetResponseDisplayNames) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1LanguagesResourceGetResponseDisplayNames) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetEn sets the En field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetResponseDisplayNames) SetEn(en *string) {
	v.En = en
	v.require(v1LanguagesResourceGetResponseDisplayNamesFieldEn)
}

func (v *V1LanguagesResourceGetResponseDisplayNames) UnmarshalJSON(data []byte) error {
	type unmarshaler V1LanguagesResourceGetResponseDisplayNames
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1LanguagesResourceGetResponseDisplayNames(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1LanguagesResourceGetResponseDisplayNames) MarshalJSON() ([]byte, error) {
	type embed V1LanguagesResourceGetResponseDisplayNames
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1LanguagesResourceGetResponseDisplayNames) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Default text direction for this language. ltr is left to right and rtl is right to left.
type V1LanguagesResourceGetResponseTextDirection string

const (
	V1LanguagesResourceGetResponseTextDirectionLtr V1LanguagesResourceGetResponseTextDirection = "ltr"
	V1LanguagesResourceGetResponseTextDirectionRtl V1LanguagesResourceGetResponseTextDirection = "rtl"
)

func NewV1LanguagesResourceGetResponseTextDirectionFromString(s string) (V1LanguagesResourceGetResponseTextDirection, error) {
	switch s {
	case "ltr":
		return V1LanguagesResourceGetResponseTextDirectionLtr, nil
	case "rtl":
		return V1LanguagesResourceGetResponseTextDirectionRtl, nil
	}
	var t V1LanguagesResourceGetResponseTextDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v V1LanguagesResourceGetResponseTextDirection) Ptr() *V1LanguagesResourceGetResponseTextDirection {
	return &v
}

var (
	v1LanguagesCollectionGetRequestFieldPageSize        = big.NewInt(1 << 0)
	v1LanguagesCollectionGetRequestFieldFieldsArray     = big.NewInt(1 << 1)
	v1LanguagesCollectionGetRequestFieldPageToken       = big.NewInt(1 << 2)
	v1LanguagesCollectionGetRequestFieldCountry         = big.NewInt(1 << 3)
	v1LanguagesCollectionGetRequestFieldBiblesAvailable = big.NewInt(1 << 4)
)

type V1LanguagesCollectionGetRequest struct {
	// The number of items to return in the collection.  Numeric values must be between 1 and 99.
	// Special value "*" is supported only when used in combination with the `fields` parameter and
	// when the client requests three or fewer fields (see `fields` parameter). When "*" is used the
	// server will return all matching items for the requested resource (no numeric page limit).
	PageSize *V1LanguagesCollectionGetRequestPageSize `json:"-" url:"page_size,omitempty"`
	// A list of top-level fields to include in each resource object. Use bracket notation to pass
	// multiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.
	// When provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.
	FieldsArray []*string `json:"-" url:"fields[],omitempty"`
	// The page token to retrieve results from.
	PageToken *string `json:"-" url:"page_token,omitempty"`
	// The ISO 3166 2 character country code
	Country *string `json:"-" url:"country,omitempty"`
	// Filter languages based on whether Bible content is available for that language.
	BiblesAvailable *bool `json:"-" url:"bibles_available,omitempty"`
	acceptLanguage  string

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1LanguagesCollectionGetRequest) AcceptLanguage() string {
	return v.acceptLanguage
}

func (v *V1LanguagesCollectionGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetRequest) SetPageSize(pageSize *V1LanguagesCollectionGetRequestPageSize) {
	v.PageSize = pageSize
	v.require(v1LanguagesCollectionGetRequestFieldPageSize)
}

// SetFieldsArray sets the FieldsArray field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetRequest) SetFieldsArray(fieldsArray []*string) {
	v.FieldsArray = fieldsArray
	v.require(v1LanguagesCollectionGetRequestFieldFieldsArray)
}

// SetPageToken sets the PageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetRequest) SetPageToken(pageToken *string) {
	v.PageToken = pageToken
	v.require(v1LanguagesCollectionGetRequestFieldPageToken)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetRequest) SetCountry(country *string) {
	v.Country = country
	v.require(v1LanguagesCollectionGetRequestFieldCountry)
}

// SetBiblesAvailable sets the BiblesAvailable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesCollectionGetRequest) SetBiblesAvailable(biblesAvailable *bool) {
	v.BiblesAvailable = biblesAvailable
	v.require(v1LanguagesCollectionGetRequestFieldBiblesAvailable)
}

var (
	v1LanguagesResourceGetRequestFieldLanguageID = big.NewInt(1 << 0)
)

type V1LanguagesResourceGetRequest struct {
	// The language identifier uses the canonical BCP 47 language code, optionally including the script subtag when it distinguishes writing systems (for example, sr-Latn vs sr-Cyrl). Region subtags are excluded because they usually represent contextual or user-specific preferences rather than the intrinsic identity of the language, with one exception: a small, enumerated set of region variants that speakers treat as distinct languages is preserved (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Every other region, plus variants and extensions, is excluded, and a request for one redirects to the canonical region-agnostic id. This keeps identifiers stable and minimal while still surfacing the variants users distinguish.
	LanguageID     string `json:"-" url:"-"`
	acceptLanguage string

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1LanguagesResourceGetRequest) AcceptLanguage() string {
	return v.acceptLanguage
}

func (v *V1LanguagesResourceGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetLanguageID sets the LanguageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1LanguagesResourceGetRequest) SetLanguageID(languageID string) {
	v.LanguageID = languageID
	v.require(v1LanguagesResourceGetRequestFieldLanguageID)
}
