// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

var (
	v1AppsPermissionsCollectionGetResponseFieldPermissions = big.NewInt(1 << 0)
)

type V1AppsPermissionsCollectionGetResponse struct {
	// Permissions the user has granted to the calling app.
	Permissions []string `json:"permissions" url:"permissions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1AppsPermissionsCollectionGetResponse) GetPermissions() []string {
	if v == nil {
		return nil
	}
	return v.Permissions
}

func (v *V1AppsPermissionsCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1AppsPermissionsCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1AppsPermissionsCollectionGetResponse) SetPermissions(permissions []string) {
	v.Permissions = permissions
	v.require(v1AppsPermissionsCollectionGetResponseFieldPermissions)
}

func (v *V1AppsPermissionsCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1AppsPermissionsCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1AppsPermissionsCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1AppsPermissionsCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1AppsPermissionsCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1AppsPermissionsCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1AppsPermissionsCollectionGetRequestFieldAppID = big.NewInt(1 << 0)
)

type V1AppsPermissionsCollectionGetRequest struct {
	// The unique identifier of the app.
	AppID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1AppsPermissionsCollectionGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1AppsPermissionsCollectionGetRequest) SetAppID(appID string) {
	v.AppID = appID
	v.require(v1AppsPermissionsCollectionGetRequestFieldAppID)
}
