// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

var (
	v1SearchQueriesCollectionGetResponseFieldData = big.NewInt(1 << 0)
)

type V1SearchQueriesCollectionGetResponse struct {
	Data []*V1SearchQueriesCollectionGetResponseDataItem `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1SearchQueriesCollectionGetResponse) GetData() []*V1SearchQueriesCollectionGetResponseDataItem {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V1SearchQueriesCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1SearchQueriesCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetResponse) SetData(data []*V1SearchQueriesCollectionGetResponseDataItem) {
	v.Data = data
	v.require(v1SearchQueriesCollectionGetResponseFieldData)
}

func (v *V1SearchQueriesCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1SearchQueriesCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1SearchQueriesCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1SearchQueriesCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1SearchQueriesCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1SearchQueriesCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// A query object: a search string a user might run, plus where it came from (e.g. a community suggestion or a trending search).
var (
	v1SearchQueriesCollectionGetResponseDataItemFieldText   = big.NewInt(1 << 0)
	v1SearchQueriesCollectionGetResponseDataItemFieldSource = big.NewInt(1 << 1)
)

type V1SearchQueriesCollectionGetResponseDataItem struct {
	// The suggested or trending search query string.
	Text string `json:"text" url:"text"`
	// Where the query came from, e.g. `community` or `trending`.
	Source *string `json:"source,omitempty" url:"source,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) GetText() string {
	if v == nil {
		return ""
	}
	return v.Text
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) GetSource() *string {
	if v == nil {
		return nil
	}
	return v.Source
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetResponseDataItem) SetText(text string) {
	v.Text = text
	v.require(v1SearchQueriesCollectionGetResponseDataItemFieldText)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetResponseDataItem) SetSource(source *string) {
	v.Source = source
	v.require(v1SearchQueriesCollectionGetResponseDataItemFieldSource)
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1SearchQueriesCollectionGetResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1SearchQueriesCollectionGetResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed V1SearchQueriesCollectionGetResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1SearchQueriesCollectionGetResponseDataItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1SearchQueriesCollectionGetRequestFieldLanguageRangesArray = big.NewInt(1 << 0)
	v1SearchQueriesCollectionGetRequestFieldQuery               = big.NewInt(1 << 1)
	v1SearchQueriesCollectionGetRequestFieldTrending            = big.NewInt(1 << 2)
)

type V1SearchQueriesCollectionGetRequest struct {
	// An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
	// Language ranges in this parameter may only be of the Basic Range format.
	LanguageRangesArray []*string `json:"-" url:"language_ranges[],omitempty"`
	// The partial query for as-you-type suggestions. Omit for trending queries.
	Query *string `json:"-" url:"query,omitempty"`
	// Return recently popular searches for the language instead of suggestions.
	Trending *bool `json:"-" url:"trending,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1SearchQueriesCollectionGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetLanguageRangesArray sets the LanguageRangesArray field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetRequest) SetLanguageRangesArray(languageRangesArray []*string) {
	v.LanguageRangesArray = languageRangesArray
	v.require(v1SearchQueriesCollectionGetRequestFieldLanguageRangesArray)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetRequest) SetQuery(query *string) {
	v.Query = query
	v.require(v1SearchQueriesCollectionGetRequestFieldQuery)
}

// SetTrending sets the Trending field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchQueriesCollectionGetRequest) SetTrending(trending *bool) {
	v.Trending = trending
	v.require(v1SearchQueriesCollectionGetRequestFieldTrending)
}
