// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

type V1SearchUnifiedCollectionGetRequestUserIntent string

const (
	V1SearchUnifiedCollectionGetRequestUserIntentUnknown   V1SearchUnifiedCollectionGetRequestUserIntent = "unknown"
	V1SearchUnifiedCollectionGetRequestUserIntentTopical   V1SearchUnifiedCollectionGetRequestUserIntent = "topical"
	V1SearchUnifiedCollectionGetRequestUserIntentText      V1SearchUnifiedCollectionGetRequestUserIntent = "text"
	V1SearchUnifiedCollectionGetRequestUserIntentReference V1SearchUnifiedCollectionGetRequestUserIntent = "reference"
)

func NewV1SearchUnifiedCollectionGetRequestUserIntentFromString(s string) (V1SearchUnifiedCollectionGetRequestUserIntent, error) {
	switch s {
	case "unknown":
		return V1SearchUnifiedCollectionGetRequestUserIntentUnknown, nil
	case "topical":
		return V1SearchUnifiedCollectionGetRequestUserIntentTopical, nil
	case "text":
		return V1SearchUnifiedCollectionGetRequestUserIntentText, nil
	case "reference":
		return V1SearchUnifiedCollectionGetRequestUserIntentReference, nil
	}
	var t V1SearchUnifiedCollectionGetRequestUserIntent
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v V1SearchUnifiedCollectionGetRequestUserIntent) Ptr() *V1SearchUnifiedCollectionGetRequestUserIntent {
	return &v
}

// A single unified, unpaginated set of search results grouped by kind: verse references and related topics. Returns one combined page of top results per kind; there is no page_size or page_token. Use the kind-specific endpoints (search-verses, search-topics) to page through the full result set for a kind.
var (
	v1SearchUnifiedCollectionGetResponseFieldVerses           = big.NewInt(1 << 0)
	v1SearchUnifiedCollectionGetResponseFieldTopics           = big.NewInt(1 << 1)
	v1SearchUnifiedCollectionGetResponseFieldUserIntent       = big.NewInt(1 << 2)
	v1SearchUnifiedCollectionGetResponseFieldDidYouMean       = big.NewInt(1 << 3)
	v1SearchUnifiedCollectionGetResponseFieldSearchInsteadFor = big.NewInt(1 << 4)
)

type V1SearchUnifiedCollectionGetResponse struct {
	Verses []*V1SearchUnifiedCollectionGetResponseVersesItem `json:"verses,omitempty" url:"verses,omitempty"`
	Topics []*V1SearchUnifiedCollectionGetResponseTopicsItem `json:"topics,omitempty" url:"topics,omitempty"`
	// The intent the Core Search service resolved for the query.
	UserIntent *string `json:"user_intent,omitempty" url:"user_intent,omitempty"`
	// Alternative spellings the search service suggests for the query.
	DidYouMean []string `json:"did_you_mean" url:"did_you_mean"`
	// A corrected query the results were actually returned for, if any.
	SearchInsteadFor *string `json:"search_instead_for,omitempty" url:"search_instead_for,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1SearchUnifiedCollectionGetResponse) GetVerses() []*V1SearchUnifiedCollectionGetResponseVersesItem {
	if v == nil {
		return nil
	}
	return v.Verses
}

func (v *V1SearchUnifiedCollectionGetResponse) GetTopics() []*V1SearchUnifiedCollectionGetResponseTopicsItem {
	if v == nil {
		return nil
	}
	return v.Topics
}

func (v *V1SearchUnifiedCollectionGetResponse) GetUserIntent() *string {
	if v == nil {
		return nil
	}
	return v.UserIntent
}

func (v *V1SearchUnifiedCollectionGetResponse) GetDidYouMean() []string {
	if v == nil {
		return nil
	}
	return v.DidYouMean
}

func (v *V1SearchUnifiedCollectionGetResponse) GetSearchInsteadFor() *string {
	if v == nil {
		return nil
	}
	return v.SearchInsteadFor
}

func (v *V1SearchUnifiedCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1SearchUnifiedCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVerses sets the Verses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponse) SetVerses(verses []*V1SearchUnifiedCollectionGetResponseVersesItem) {
	v.Verses = verses
	v.require(v1SearchUnifiedCollectionGetResponseFieldVerses)
}

// SetTopics sets the Topics field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponse) SetTopics(topics []*V1SearchUnifiedCollectionGetResponseTopicsItem) {
	v.Topics = topics
	v.require(v1SearchUnifiedCollectionGetResponseFieldTopics)
}

// SetUserIntent sets the UserIntent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponse) SetUserIntent(userIntent *string) {
	v.UserIntent = userIntent
	v.require(v1SearchUnifiedCollectionGetResponseFieldUserIntent)
}

// SetDidYouMean sets the DidYouMean field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponse) SetDidYouMean(didYouMean []string) {
	v.DidYouMean = didYouMean
	v.require(v1SearchUnifiedCollectionGetResponseFieldDidYouMean)
}

// SetSearchInsteadFor sets the SearchInsteadFor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponse) SetSearchInsteadFor(searchInsteadFor *string) {
	v.SearchInsteadFor = searchInsteadFor
	v.require(v1SearchUnifiedCollectionGetResponseFieldSearchInsteadFor)
}

func (v *V1SearchUnifiedCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1SearchUnifiedCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1SearchUnifiedCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1SearchUnifiedCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1SearchUnifiedCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1SearchUnifiedCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// A topic related to the query, for pivoting to other verses in the same topic.
var (
	v1SearchUnifiedCollectionGetResponseTopicsItemFieldID        = big.NewInt(1 << 0)
	v1SearchUnifiedCollectionGetResponseTopicsItemFieldText      = big.NewInt(1 << 1)
	v1SearchUnifiedCollectionGetResponseTopicsItemFieldSubtopics = big.NewInt(1 << 2)
)

type V1SearchUnifiedCollectionGetResponseTopicsItem struct {
	// The topic's identifier in the Core Search catalog.
	ID *int `json:"id,omitempty" url:"id,omitempty"`
	// The topic label.
	Text string `json:"text" url:"text"`
	// Related subtopic labels, if any.
	Subtopics []string `json:"subtopics" url:"subtopics"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) GetID() *int {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) GetText() string {
	if v == nil {
		return ""
	}
	return v.Text
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) GetSubtopics() []string {
	if v == nil {
		return nil
	}
	return v.Subtopics
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) SetID(id *int) {
	v.ID = id
	v.require(v1SearchUnifiedCollectionGetResponseTopicsItemFieldID)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) SetText(text string) {
	v.Text = text
	v.require(v1SearchUnifiedCollectionGetResponseTopicsItemFieldText)
}

// SetSubtopics sets the Subtopics field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) SetSubtopics(subtopics []string) {
	v.Subtopics = subtopics
	v.require(v1SearchUnifiedCollectionGetResponseTopicsItemFieldSubtopics)
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1SearchUnifiedCollectionGetResponseTopicsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1SearchUnifiedCollectionGetResponseTopicsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) MarshalJSON() ([]byte, error) {
	type embed V1SearchUnifiedCollectionGetResponseTopicsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1SearchUnifiedCollectionGetResponseTopicsItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// A verse result: a scripture reference and metadata only, never passage text. Resolve verse text through the licensed-content endpoint.
var (
	v1SearchUnifiedCollectionGetResponseVersesItemFieldReference = big.NewInt(1 << 0)
)

type V1SearchUnifiedCollectionGetResponseVersesItem struct {
	// USFM scripture reference for the matched verse.
	Reference string `json:"reference" url:"reference"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) GetReference() string {
	if v == nil {
		return ""
	}
	return v.Reference
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetReference sets the Reference field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetResponseVersesItem) SetReference(reference string) {
	v.Reference = reference
	v.require(v1SearchUnifiedCollectionGetResponseVersesItemFieldReference)
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1SearchUnifiedCollectionGetResponseVersesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1SearchUnifiedCollectionGetResponseVersesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) MarshalJSON() ([]byte, error) {
	type embed V1SearchUnifiedCollectionGetResponseVersesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1SearchUnifiedCollectionGetResponseVersesItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1SearchUnifiedCollectionGetRequestFieldQuery               = big.NewInt(1 << 0)
	v1SearchUnifiedCollectionGetRequestFieldBibleID             = big.NewInt(1 << 1)
	v1SearchUnifiedCollectionGetRequestFieldLanguageRangesArray = big.NewInt(1 << 2)
	v1SearchUnifiedCollectionGetRequestFieldUserIntent          = big.NewInt(1 << 3)
	v1SearchUnifiedCollectionGetRequestFieldFieldsArray         = big.NewInt(1 << 4)
)

type V1SearchUnifiedCollectionGetRequest struct {
	// The search query string used to find matching results.
	Query string `json:"-" url:"query"`
	// The Bible version identifier
	BibleID int `json:"-" url:"bible_id"`
	// An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
	// Language ranges in this parameter may only be of the Basic Range format.
	LanguageRangesArray []*string `json:"-" url:"language_ranges[],omitempty"`
	// The searcher's intent. Defaults to unknown, matching the Core Search service.
	UserIntent *V1SearchUnifiedCollectionGetRequestUserIntent `json:"-" url:"user_intent,omitempty"`
	// Result kinds to include: `verses` and/or `topics`. Use bracket notation to pass multiple
	// values, for example `fields[]=verses&fields[]=topics`. Omit to return all kinds. Query
	// metadata is always included.
	FieldsArray []*string `json:"-" url:"fields[],omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1SearchUnifiedCollectionGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetRequest) SetQuery(query string) {
	v.Query = query
	v.require(v1SearchUnifiedCollectionGetRequestFieldQuery)
}

// SetBibleID sets the BibleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetRequest) SetBibleID(bibleID int) {
	v.BibleID = bibleID
	v.require(v1SearchUnifiedCollectionGetRequestFieldBibleID)
}

// SetLanguageRangesArray sets the LanguageRangesArray field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetRequest) SetLanguageRangesArray(languageRangesArray []*string) {
	v.LanguageRangesArray = languageRangesArray
	v.require(v1SearchUnifiedCollectionGetRequestFieldLanguageRangesArray)
}

// SetUserIntent sets the UserIntent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetRequest) SetUserIntent(userIntent *V1SearchUnifiedCollectionGetRequestUserIntent) {
	v.UserIntent = userIntent
	v.require(v1SearchUnifiedCollectionGetRequestFieldUserIntent)
}

// SetFieldsArray sets the FieldsArray field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1SearchUnifiedCollectionGetRequest) SetFieldsArray(fieldsArray []*string) {
	v.FieldsArray = fieldsArray
	v.require(v1SearchUnifiedCollectionGetRequestFieldFieldsArray)
}
