// Code generated by Fern. DO NOT EDIT.

package platform

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	big "math/big"
)

var (
	v1VerseOfTheDaysCanonicalCollectionGetResponseFieldData = big.NewInt(1 << 0)
)

type V1VerseOfTheDaysCanonicalCollectionGetResponse struct {
	Data []*V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) GetData() []*V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) SetData(data []*V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) {
	v.Data = data
	v.require(v1VerseOfTheDaysCanonicalCollectionGetResponseFieldData)
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1VerseOfTheDaysCanonicalCollectionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1VerseOfTheDaysCanonicalCollectionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1VerseOfTheDaysCanonicalCollectionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1VerseOfTheDaysCanonicalCollectionGetResponseDataItemFieldDay       = big.NewInt(1 << 0)
	v1VerseOfTheDaysCanonicalCollectionGetResponseDataItemFieldPassageID = big.NewInt(1 << 1)
)

type V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem struct {
	Day int `json:"day" url:"day"`
	// The passage identifier
	PassageID string `json:"passage_id" url:"passage_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) GetDay() int {
	if v == nil {
		return 0
	}
	return v.Day
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) GetPassageID() string {
	if v == nil {
		return ""
	}
	return v.PassageID
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetDay sets the Day field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) SetDay(day int) {
	v.Day = day
	v.require(v1VerseOfTheDaysCanonicalCollectionGetResponseDataItemFieldDay)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1VerseOfTheDaysCanonicalCollectionGetResponseDataItemFieldPassageID)
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1VerseOfTheDaysCanonicalCollectionGetResponseDataItem) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1VerseOfTheDaysCanonicalResourceGetResponseFieldDay       = big.NewInt(1 << 0)
	v1VerseOfTheDaysCanonicalResourceGetResponseFieldPassageID = big.NewInt(1 << 1)
)

type V1VerseOfTheDaysCanonicalResourceGetResponse struct {
	Day int `json:"day" url:"day"`
	// The passage identifier
	PassageID string `json:"passage_id" url:"passage_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) GetDay() int {
	if v == nil {
		return 0
	}
	return v.Day
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) GetPassageID() string {
	if v == nil {
		return ""
	}
	return v.PassageID
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetDay sets the Day field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) SetDay(day int) {
	v.Day = day
	v.require(v1VerseOfTheDaysCanonicalResourceGetResponseFieldDay)
}

// SetPassageID sets the PassageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) SetPassageID(passageID string) {
	v.PassageID = passageID
	v.require(v1VerseOfTheDaysCanonicalResourceGetResponseFieldPassageID)
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V1VerseOfTheDaysCanonicalResourceGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V1VerseOfTheDaysCanonicalResourceGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) MarshalJSON() ([]byte, error) {
	type embed V1VerseOfTheDaysCanonicalResourceGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V1VerseOfTheDaysCanonicalResourceGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v1VerseOfTheDaysCanonicalResourceGetRequestFieldDay = big.NewInt(1 << 0)
)

type V1VerseOfTheDaysCanonicalResourceGetRequest struct {
	// The day of the year (1-366)
	Day int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V1VerseOfTheDaysCanonicalResourceGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetDay sets the Day field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V1VerseOfTheDaysCanonicalResourceGetRequest) SetDay(day int) {
	v.Day = day
	v.require(v1VerseOfTheDaysCanonicalResourceGetRequestFieldDay)
}
