// Code generated by Fern. DO NOT EDIT.

package searchverses

import (
	context "context"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Search for Bible verses by query, returning a paginated list of verse references. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint. The bible_id determines the language searched, so this endpoint takes no language parameter. Use page_size and page_token to page through the full result set.
func (c *Client) V1SearchVersesCollectionGet(
	ctx context.Context,
	request *platform.V1SearchVersesCollectionGetRequest,
	opts ...option.RequestOption,
) (*platform.V1SearchVersesCollectionGetResponse, error) {
	response, err := c.WithRawResponse.V1SearchVersesCollectionGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
