# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v1languages_collection_get_response_data_item import V1LanguagesCollectionGetResponseDataItem


class V1LanguagesCollectionGetResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[V1LanguagesCollectionGetResponseDataItem]] = None
    next_page_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token to send to server when retrieving the next page of results.
    """

    total_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of languages in collection matching parameters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
