# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .v1fonts_collection_get_response import V1FontsCollectionGetResponse
    from .v1fonts_collection_get_response_data_item import V1FontsCollectionGetResponseDataItem
    from .v1fonts_collection_get_response_data_item_variants_item import (
        V1FontsCollectionGetResponseDataItemVariantsItem,
    )
    from .v1fonts_collection_get_response_data_item_variants_item_sources_item import (
        V1FontsCollectionGetResponseDataItemVariantsItemSourcesItem,
    )
    from .v1fonts_collection_get_response_data_item_variants_item_sources_item_format import (
        V1FontsCollectionGetResponseDataItemVariantsItemSourcesItemFormat,
    )
    from .v1fonts_collection_get_response_data_item_variants_item_style import (
        V1FontsCollectionGetResponseDataItemVariantsItemStyle,
    )
    from .v1fonts_resource_get_response import V1FontsResourceGetResponse
    from .v1fonts_resource_get_response_variants_item import V1FontsResourceGetResponseVariantsItem
    from .v1fonts_resource_get_response_variants_item_sources_item import (
        V1FontsResourceGetResponseVariantsItemSourcesItem,
    )
    from .v1fonts_resource_get_response_variants_item_sources_item_format import (
        V1FontsResourceGetResponseVariantsItemSourcesItemFormat,
    )
    from .v1fonts_resource_get_response_variants_item_style import V1FontsResourceGetResponseVariantsItemStyle
_dynamic_imports: typing.Dict[str, str] = {
    "V1FontsCollectionGetResponse": ".v1fonts_collection_get_response",
    "V1FontsCollectionGetResponseDataItem": ".v1fonts_collection_get_response_data_item",
    "V1FontsCollectionGetResponseDataItemVariantsItem": ".v1fonts_collection_get_response_data_item_variants_item",
    "V1FontsCollectionGetResponseDataItemVariantsItemSourcesItem": ".v1fonts_collection_get_response_data_item_variants_item_sources_item",
    "V1FontsCollectionGetResponseDataItemVariantsItemSourcesItemFormat": ".v1fonts_collection_get_response_data_item_variants_item_sources_item_format",
    "V1FontsCollectionGetResponseDataItemVariantsItemStyle": ".v1fonts_collection_get_response_data_item_variants_item_style",
    "V1FontsResourceGetResponse": ".v1fonts_resource_get_response",
    "V1FontsResourceGetResponseVariantsItem": ".v1fonts_resource_get_response_variants_item",
    "V1FontsResourceGetResponseVariantsItemSourcesItem": ".v1fonts_resource_get_response_variants_item_sources_item",
    "V1FontsResourceGetResponseVariantsItemSourcesItemFormat": ".v1fonts_resource_get_response_variants_item_sources_item_format",
    "V1FontsResourceGetResponseVariantsItemStyle": ".v1fonts_resource_get_response_variants_item_style",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "V1FontsCollectionGetResponse",
    "V1FontsCollectionGetResponseDataItem",
    "V1FontsCollectionGetResponseDataItemVariantsItem",
    "V1FontsCollectionGetResponseDataItemVariantsItemSourcesItem",
    "V1FontsCollectionGetResponseDataItemVariantsItemSourcesItemFormat",
    "V1FontsCollectionGetResponseDataItemVariantsItemStyle",
    "V1FontsResourceGetResponse",
    "V1FontsResourceGetResponseVariantsItem",
    "V1FontsResourceGetResponseVariantsItemSourcesItem",
    "V1FontsResourceGetResponseVariantsItemSourcesItemFormat",
    "V1FontsResourceGetResponseVariantsItemStyle",
]
