# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v1fonts_collection_get_response_data_item_variants_item import V1FontsCollectionGetResponseDataItemVariantsItem


class V1FontsCollectionGetResponseDataItem(UniversalBaseModel):
    """
    A font family resource with available variants and CDN-backed source files.
    """

    id: int = pydantic.Field()
    """
    Stable integer identifier for the font family.
    """

    slug: str = pydantic.Field()
    """
    Stable URL-safe identifier for the font family.
    """

    family: str = pydantic.Field()
    """
    Canonical font-family name clients should use.
    """

    variants: typing.List[V1FontsCollectionGetResponseDataItemVariantsItem] = pydantic.Field()
    """
    Available faces within this font family.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
