# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class V1OrganizationsCollectionGetResponseDataItemAddressAdministrativeAreaLevel1(UniversalBaseModel):
    short_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The short name of the place, e.g. "OK" for Oklahoma.
    """

    long_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The long name of the place, e.g. "Oklahoma" for the state of Oklahoma.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
