# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSearchVersesClient, RawSearchVersesClient
from .types.v1search_verses_collection_get_request_user_intent import V1SearchVersesCollectionGetRequestUserIntent
from .types.v1search_verses_collection_get_response import V1SearchVersesCollectionGetResponse


class SearchVersesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchVersesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchVersesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchVersesClient
        """
        return self._raw_client

    def v1search_verses_collection_get(
        self,
        *,
        query: str,
        bible_id: int,
        user_intent: typing.Optional[V1SearchVersesCollectionGetRequestUserIntent] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1SearchVersesCollectionGetResponse:
        """
        Search for Bible verses by query, returning a paginated list of verse references. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint. The bible_id determines the language searched, so this endpoint takes no language parameter. Use page_size and page_token to page through the full result set.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        bible_id : int
            The Bible version identifier

        user_intent : typing.Optional[V1SearchVersesCollectionGetRequestUserIntent]
            The searcher's intent. Defaults to unknown, matching the Core Search service.

        page_size : typing.Optional[int]
            The number of verse results to return in the collection. Must be between 1 and 99.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1SearchVersesCollectionGetResponse
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.search_verses.v1search_verses_collection_get(
            query="query",
            bible_id=1,
            page_token="eyJzdGFydF9hdCI6IDI2fQ==",
        )
        """
        _response = self._raw_client.v1search_verses_collection_get(
            query=query,
            bible_id=bible_id,
            user_intent=user_intent,
            page_size=page_size,
            page_token=page_token,
            request_options=request_options,
        )
        return _response.data


class AsyncSearchVersesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchVersesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchVersesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchVersesClient
        """
        return self._raw_client

    async def v1search_verses_collection_get(
        self,
        *,
        query: str,
        bible_id: int,
        user_intent: typing.Optional[V1SearchVersesCollectionGetRequestUserIntent] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1SearchVersesCollectionGetResponse:
        """
        Search for Bible verses by query, returning a paginated list of verse references. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint. The bible_id determines the language searched, so this endpoint takes no language parameter. Use page_size and page_token to page through the full result set.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        bible_id : int
            The Bible version identifier

        user_intent : typing.Optional[V1SearchVersesCollectionGetRequestUserIntent]
            The searcher's intent. Defaults to unknown, matching the Core Search service.

        page_size : typing.Optional[int]
            The number of verse results to return in the collection. Must be between 1 and 99.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1SearchVersesCollectionGetResponse
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search_verses.v1search_verses_collection_get(
                query="query",
                bible_id=1,
                page_token="eyJzdGFydF9hdCI6IDI2fQ==",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1search_verses_collection_get(
            query=query,
            bible_id=bible_id,
            user_intent=user_intent,
            page_size=page_size,
            page_token=page_token,
            request_options=request_options,
        )
        return _response.data
