# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class V1HighlightsCollectionGetResponseDataItem(UniversalBaseModel):
    bible_id: int = pydantic.Field()
    """
    Bible version identifier
    """

    passage_id: str = pydantic.Field()
    """
    The passage identifier (verse USFM format)
    """

    color: str = pydantic.Field()
    """
    The highlight color in hex format
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
