# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v1highlights_collection_get_response_data_item import V1HighlightsCollectionGetResponseDataItem


class V1HighlightsCollectionGetResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[V1HighlightsCollectionGetResponseDataItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
