// Code generated by Fern. DO NOT EDIT.

package searchunified

import (
	context "context"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Search for Bible verses and related topics by query, returning a single unified set of results across all content kinds. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint.
//
// This endpoint is unpaginated: it returns one combined page of top results per kind and exposes no page_size or page_token parameters. Use the kind-specific endpoints (search-verses, search-topics) when you need to page through the full result set for a single kind.
func (c *Client) V1SearchUnifiedCollectionGet(
	ctx context.Context,
	request *platform.V1SearchUnifiedCollectionGetRequest,
	opts ...option.RequestOption,
) (*platform.V1SearchUnifiedCollectionGetResponse, error) {
	response, err := c.WithRawResponse.V1SearchUnifiedCollectionGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
