# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1verse_of_the_days_canonical_collection_get_response import V1VerseOfTheDaysCanonicalCollectionGetResponse
from .types.v1verse_of_the_days_canonical_resource_get_response import V1VerseOfTheDaysCanonicalResourceGetResponse
from pydantic import ValidationError


class RawVerseOfTheDaysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1verse_of_the_days_canonical_collection_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse]]:
        """
        January 1 is day 1 and December 31 is day 365 (or 366 in a leap year).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse]]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/verse-of-the-days",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def v1verse_of_the_days_canonical_resource_get(
        self, day: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[V1VerseOfTheDaysCanonicalResourceGetResponse]:
        """
        Day is the day of the year (1-366).

        Parameters
        ----------
        day : int
            The day of the year (1-366)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1VerseOfTheDaysCanonicalResourceGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/verse-of-the-days/{encode_path_param(day)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1VerseOfTheDaysCanonicalResourceGetResponse,
                    parse_obj_as(
                        type_=V1VerseOfTheDaysCanonicalResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawVerseOfTheDaysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1verse_of_the_days_canonical_collection_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse]]:
        """
        January 1 is day 1 and December 31 is day 365 (or 366 in a leap year).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse]]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/verse-of-the-days",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1VerseOfTheDaysCanonicalCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def v1verse_of_the_days_canonical_resource_get(
        self, day: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[V1VerseOfTheDaysCanonicalResourceGetResponse]:
        """
        Day is the day of the year (1-366).

        Parameters
        ----------
        day : int
            The day of the year (1-366)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1VerseOfTheDaysCanonicalResourceGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/verse-of-the-days/{encode_path_param(day)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1VerseOfTheDaysCanonicalResourceGetResponse,
                    parse_obj_as(
                        type_=V1VerseOfTheDaysCanonicalResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
