// Code generated by Fern. DO NOT EDIT.

package licenses

import (
	context "context"
	http "net/http"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) V1LicensesCollectionGet(
	ctx context.Context,
	request *platform.V1LicensesCollectionGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*platform.V1LicensesCollectionGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := baseURL + "/v1/licenses"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	var response *platform.V1LicensesCollectionGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*platform.V1LicensesCollectionGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
