# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSearchTopicsClient, RawSearchTopicsClient
from .types.v1search_topics_collection_get_response import V1SearchTopicsCollectionGetResponse


class SearchTopicsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchTopicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchTopicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchTopicsClient
        """
        return self._raw_client

    def v1search_topics_collection_get(
        self,
        *,
        query: str,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1SearchTopicsCollectionGetResponse:
        """
        Returns the set of topics (id, text, subtopics) related to a query, for pivoting to other verses in the same topic.

        This endpoint is unpaginated: Core Search returns a fixed set of topics and exposes no page_size or page_token parameters. Query metadata (did_you_mean, search_instead_for) is always included.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1SearchTopicsCollectionGetResponse
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.search_topics.v1search_topics_collection_get(
            query="query",
            language_ranges=["en"],
        )
        """
        _response = self._raw_client.v1search_topics_collection_get(
            query=query, language_ranges=language_ranges, request_options=request_options
        )
        return _response.data


class AsyncSearchTopicsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchTopicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchTopicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchTopicsClient
        """
        return self._raw_client

    async def v1search_topics_collection_get(
        self,
        *,
        query: str,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1SearchTopicsCollectionGetResponse:
        """
        Returns the set of topics (id, text, subtopics) related to a query, for pivoting to other verses in the same topic.

        This endpoint is unpaginated: Core Search returns a fixed set of topics and exposes no page_size or page_token parameters. Query metadata (did_you_mean, search_instead_for) is always included.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1SearchTopicsCollectionGetResponse
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search_topics.v1search_topics_collection_get(
                query="query",
                language_ranges=["en"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1search_topics_collection_get(
            query=query, language_ranges=language_ranges, request_options=request_options
        )
        return _response.data
