# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from .types.v1highlights_collection_get_response import V1HighlightsCollectionGetResponse
from .types.v1highlights_collection_post_request_highlight import V1HighlightsCollectionPostRequestHighlight
from .types.v1highlights_collection_post_response import V1HighlightsCollectionPostResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawHighlightsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1highlights_collection_get(
        self, *, bible_id: int, passage_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[V1HighlightsCollectionGetResponse]]:
        """
        The response will return a color per verse without ranges.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        passage_id : str
            The passage identifier (verse or chapter USFM format)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[V1HighlightsCollectionGetResponse]]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/highlights",
            method="GET",
            params={
                "bible_id": bible_id,
                "passage_id": passage_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1HighlightsCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1HighlightsCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def v1highlights_collection_post(
        self,
        *,
        request_id: str,
        highlight: V1HighlightsCollectionPostRequestHighlight,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[V1HighlightsCollectionPostResponse]:
        """
        Verse ranges may be used in the POST body passage_id attribute.

        Parameters
        ----------
        request_id : str
            Request UUID for idempotent create retries.

        highlight : V1HighlightsCollectionPostRequestHighlight

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1HighlightsCollectionPostResponse]
            Highlight(s) created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/highlights",
            method="POST",
            json={
                "request_id": request_id,
                "highlight": convert_and_respect_annotation_metadata(
                    object_=highlight, annotation=V1HighlightsCollectionPostRequestHighlight, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1HighlightsCollectionPostResponse,
                    parse_obj_as(
                        type_=V1HighlightsCollectionPostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def v1highlights_resource_delete(
        self, passage_id_path: str, *, bible_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Clear highlights for a passage.

        Parameters
        ----------
        passage_id_path : str
            The passage identifier (verse or chapter USFM format)

        bible_id : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/highlights/{encode_path_param(passage_id_path)}",
            method="DELETE",
            params={
                "bible_id": bible_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawHighlightsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1highlights_collection_get(
        self, *, bible_id: int, passage_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[V1HighlightsCollectionGetResponse]]:
        """
        The response will return a color per verse without ranges.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        passage_id : str
            The passage identifier (verse or chapter USFM format)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[V1HighlightsCollectionGetResponse]]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/highlights",
            method="GET",
            params={
                "bible_id": bible_id,
                "passage_id": passage_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1HighlightsCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1HighlightsCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def v1highlights_collection_post(
        self,
        *,
        request_id: str,
        highlight: V1HighlightsCollectionPostRequestHighlight,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[V1HighlightsCollectionPostResponse]:
        """
        Verse ranges may be used in the POST body passage_id attribute.

        Parameters
        ----------
        request_id : str
            Request UUID for idempotent create retries.

        highlight : V1HighlightsCollectionPostRequestHighlight

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1HighlightsCollectionPostResponse]
            Highlight(s) created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/highlights",
            method="POST",
            json={
                "request_id": request_id,
                "highlight": convert_and_respect_annotation_metadata(
                    object_=highlight, annotation=V1HighlightsCollectionPostRequestHighlight, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1HighlightsCollectionPostResponse,
                    parse_obj_as(
                        type_=V1HighlightsCollectionPostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def v1highlights_resource_delete(
        self, passage_id_path: str, *, bible_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Clear highlights for a passage.

        Parameters
        ----------
        passage_id_path : str
            The passage identifier (verse or chapter USFM format)

        bible_id : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/highlights/{encode_path_param(passage_id_path)}",
            method="DELETE",
            params={
                "bible_id": bible_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
