# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .book_canon import BookCanon
from .book_chapters_item import BookChaptersItem
from .book_intro import BookIntro


class Book(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book identifier
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book title
    """

    full_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full book title if available
    """

    abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book name abbreviation if provided by the publisher
    """

    canon: typing.Optional[BookCanon] = pydantic.Field(default=None)
    """
    Canon identifier
    """

    chapters: typing.Optional[typing.List[BookChaptersItem]] = pydantic.Field(default=None)
    """
    Chapters in the book
    """

    intro: typing.Optional[BookIntro] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
