# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fonts_data_item_variants_item_sources_item_format import FontsDataItemVariantsItemSourcesItemFormat


class FontsDataItemVariantsItemSourcesItem(UniversalBaseModel):
    format: FontsDataItemVariantsItemSourcesItemFormat = pydantic.Field()
    """
    The file format for this source asset.
    """

    url: str = pydantic.Field()
    """
    Fully qualified CDN URL for this font source file.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
