# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fonts_data_item_variants_item_sources_item import FontsDataItemVariantsItemSourcesItem
from .fonts_data_item_variants_item_style import FontsDataItemVariantsItemStyle


class FontsDataItemVariantsItem(UniversalBaseModel):
    weight: int = pydantic.Field()
    """
    Numeric font weight for this variant.
    """

    style: FontsDataItemVariantsItemStyle = pydantic.Field()
    """
    Font style for this variant.
    """

    sources: typing.List[FontsDataItemVariantsItemSourcesItem] = pydantic.Field()
    """
    CDN assets available for this specific weight and style.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
