# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organizations_data_item import OrganizationsDataItem


class Organizations(UniversalBaseModel):
    data: typing.Optional[typing.List[OrganizationsDataItem]] = None
    next_page_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token to send to server when retrieving the next page of results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
