# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .organization_address_administrative_area_level1 import OrganizationAddressAdministrativeAreaLevel1
from .organization_address_country import OrganizationAddressCountry
from .organization_address_locality import OrganizationAddressLocality


class OrganizationAddress(UniversalBaseModel):
    """
    The Address Schema belonging to the Organization Resource in the Platform.
    """

    formatted_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The human-readable address of the organization.
    """

    formatted_locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    A less specific and more broad field that can be a combination of different regional fields.
    """

    place_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The textual identifier that uniquely identifies a place.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The location of the address profile.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The location of the address profile.
    """

    administrative_area_level1: typing_extensions.Annotated[
        typing.Optional[OrganizationAddressAdministrativeAreaLevel1],
        FieldMetadata(alias="administrative_area_level_1"),
        pydantic.Field(alias="administrative_area_level_1"),
    ] = None
    locality: typing.Optional[OrganizationAddressLocality] = None
    country: typing.Optional[OrganizationAddressCountry] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
