# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SearchUnifiedVersesItem(UniversalBaseModel):
    """
    A verse result: a scripture reference and metadata only, never passage text. Resolve verse text through the licensed-content endpoint.
    """

    reference: str = pydantic.Field()
    """
    USFM scripture reference for the matched verse.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
