# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SearchQuery(UniversalBaseModel):
    """
    A query object: a search string a user might run, plus where it came from (e.g. a community suggestion or a trending search).
    """

    text: str = pydantic.Field()
    """
    The suggested or trending search query string.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Where the query came from, e.g. `community` or `trending`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
