# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SpotlightPublishDateResponse(UniversalBaseModel):
    """
    Manifest entry state returned after a publish-date assignment.
    """

    slug: str = pydantic.Field()
    """
    Slug of the updated manifest entry.
    """

    publish_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishDate"),
        pydantic.Field(alias="publishDate", description="The assigned go-live month (YYYY-MM), or null if cleared."),
    ] = None
    """
    The assigned go-live month (YYYY-MM), or null if cleared.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
