# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.bibles_books_chapters_collection_get_response import BiblesBooksChaptersCollectionGetResponse
from .types.bibles_books_chapters_resource_get_response import BiblesBooksChaptersResourceGetResponse
from .types.bibles_books_chapters_verses_collection_get_response import BiblesBooksChaptersVersesCollectionGetResponse
from .types.bibles_books_chapters_verses_resource_get_response import BiblesBooksChaptersVersesResourceGetResponse
from .types.bibles_books_collection_get_request_canon import BiblesBooksCollectionGetRequestCanon
from .types.bibles_books_collection_get_response import BiblesBooksCollectionGetResponse
from .types.bibles_books_resource_get_response import BiblesBooksResourceGetResponse
from .types.bibles_collection_get_request_page_size import BiblesCollectionGetRequestPageSize
from .types.bibles_collection_get_response import BiblesCollectionGetResponse
from .types.bibles_index_collection_get_response import BiblesIndexCollectionGetResponse
from .types.bibles_passages_resource_get_request_format import BiblesPassagesResourceGetRequestFormat
from .types.bibles_passages_resource_get_response import BiblesPassagesResourceGetResponse
from .types.bibles_resource_get_response import BiblesResourceGetResponse
from pydantic import ValidationError


class RawBiblesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def collection_get(
        self,
        *,
        all_available: typing.Optional[bool] = None,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        license_id: typing.Optional[int] = None,
        page_size: typing.Optional[BiblesCollectionGetRequestPageSize] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Optional[BiblesCollectionGetResponse]]:
        """
        Retrieves a paginated list of Bible versions available.
        When multiple language_ranges parameters are specified, the set of Bibles returned will be from
        the first language range which has available Bibles.

        Parameters
        ----------
        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        license_id : typing.Optional[int]
            Filter Bibles by a license identifier

        page_size : typing.Optional[BiblesCollectionGetRequestPageSize]
            The number of items to return in the collection.  Numeric values must be between 1 and 99.
            Special value "*" is supported only when used in combination with the `fields` parameter and
            when the client requests three or fewer fields (see `fields` parameter). When "*" is used the
            server will return all matching items for the requested resource (no numeric page limit).

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of top-level fields to include in each resource object. Use bracket notation to pass
            multiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.
            When provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[BiblesCollectionGetResponse]]
            Indicates that the request was successful.  Returns a JSON array of Bible resources in the
            response body, each containing metadata about a specific translation.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/bibles",
            method="GET",
            params={
                "all_available": all_available,
                "language_ranges[]": language_ranges,
                "license_id": license_id,
                "page_size": page_size,
                "fields[]": fields,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def resource_get(
        self, bible_id_path: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[BiblesResourceGetResponse]:
        """
        Get a Bible resource for a single Bible version.
        This does not include the Bible's text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesResourceGetResponse]
            Indicates that the Bible resource was found and returned successfully.  The response body contains
            a JSON object describing the requested translation in detail.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def index_collection_get(
        self, bible_id_path: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[BiblesIndexCollectionGetResponse]:
        """
        Retrieves the indexing structure for the specified Bible version.  This includes the full hierarchy of
        books, chapters, and verse counts.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesIndexCollectionGetResponse]
            The index resource was returned successfully.  You will receive a JSON object detailing the
            organization of books, chapters, and verse counts for the requested Bible version.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/index",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesIndexCollectionGetResponse,
                    parse_obj_as(
                        type_=BiblesIndexCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def passages_resource_get(
        self,
        bible_id_path: int,
        passage_id_path: str,
        *,
        format: typing.Optional[BiblesPassagesResourceGetRequestFormat] = None,
        include_headings: typing.Optional[bool] = None,
        include_notes: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BiblesPassagesResourceGetResponse]:
        """
        Returns the specified scripture passage in the requested format. Headings and
        notes may be included via query parameters, but only when format=html. They
        are omitted when format=text. The response includes content text and metadata
        such as verse ranges and formatting details.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        passage_id_path : str
            The passage identifier (verse or chapter USFM format)

        format : typing.Optional[BiblesPassagesResourceGetRequestFormat]
            The desired Bible content format (text or html). Headings and notes are included only when format=html; format=text returns verse text without them.

        include_headings : typing.Optional[bool]
            Whether or not headings should be included in the Bible content. Headings are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.

        include_notes : typing.Optional[bool]
            Whether or not notes should be included in the Bible content. Notes are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesPassagesResourceGetResponse]
            The passage was retrieved successfully in the desired format. The response
            body contains a JSON object with verse text and formatting metadata.
            Optional headings and notes are present only when format=html.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/passages/{encode_path_param(passage_id_path)}",
            method="GET",
            params={
                "format": format,
                "include_headings": include_headings,
                "include_notes": include_notes,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesPassagesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesPassagesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_collection_get(
        self,
        bible_id_path: int,
        *,
        canon: typing.Optional[BiblesBooksCollectionGetRequestCanon] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Optional[BiblesBooksCollectionGetResponse]]:
        """
        Retrieves the list of books (e.g. Genesis, Exodus) for the specified Bible version.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        canon : typing.Optional[BiblesBooksCollectionGetRequestCanon]
            The Canon to filter results by

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[BiblesBooksCollectionGetResponse]]
            The collection of books was returned successfully.  The JSON array in the response body details
            book identifiers, names, and order within the Bible version.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books",
            method="GET",
            params={
                "canon": canon,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_resource_get(
        self, bible_id_path: int, book_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[BiblesBooksResourceGetResponse]:
        """
        Get a Book resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesBooksResourceGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_chapters_collection_get(
        self, bible_id_path: int, book_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[BiblesBooksChaptersCollectionGetResponse]]:
        """
        Get a collection of Chapters for the given Bible and Book

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[BiblesBooksChaptersCollectionGetResponse]]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksChaptersCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksChaptersCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_chapters_resource_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BiblesBooksChaptersResourceGetResponse]:
        """
        Get a Chapter resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesBooksChaptersResourceGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksChaptersResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksChaptersResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_chapters_verses_collection_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse]]:
        """
        Get a collection of Verses for a Chapter.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse]]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}/verses",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def books_chapters_verses_resource_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        verse_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BiblesBooksChaptersVersesResourceGetResponse]:
        """
        Get a Verse resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        verse_id : str
            The Bible Verse identifier pulled from part of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BiblesBooksChaptersVersesResourceGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}/verses/{encode_path_param(verse_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksChaptersVersesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksChaptersVersesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBiblesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def collection_get(
        self,
        *,
        all_available: typing.Optional[bool] = None,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        license_id: typing.Optional[int] = None,
        page_size: typing.Optional[BiblesCollectionGetRequestPageSize] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Optional[BiblesCollectionGetResponse]]:
        """
        Retrieves a paginated list of Bible versions available.
        When multiple language_ranges parameters are specified, the set of Bibles returned will be from
        the first language range which has available Bibles.

        Parameters
        ----------
        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        license_id : typing.Optional[int]
            Filter Bibles by a license identifier

        page_size : typing.Optional[BiblesCollectionGetRequestPageSize]
            The number of items to return in the collection.  Numeric values must be between 1 and 99.
            Special value "*" is supported only when used in combination with the `fields` parameter and
            when the client requests three or fewer fields (see `fields` parameter). When "*" is used the
            server will return all matching items for the requested resource (no numeric page limit).

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of top-level fields to include in each resource object. Use bracket notation to pass
            multiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.
            When provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[BiblesCollectionGetResponse]]
            Indicates that the request was successful.  Returns a JSON array of Bible resources in the
            response body, each containing metadata about a specific translation.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/bibles",
            method="GET",
            params={
                "all_available": all_available,
                "language_ranges[]": language_ranges,
                "license_id": license_id,
                "page_size": page_size,
                "fields[]": fields,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def resource_get(
        self, bible_id_path: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[BiblesResourceGetResponse]:
        """
        Get a Bible resource for a single Bible version.
        This does not include the Bible's text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesResourceGetResponse]
            Indicates that the Bible resource was found and returned successfully.  The response body contains
            a JSON object describing the requested translation in detail.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def index_collection_get(
        self, bible_id_path: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[BiblesIndexCollectionGetResponse]:
        """
        Retrieves the indexing structure for the specified Bible version.  This includes the full hierarchy of
        books, chapters, and verse counts.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesIndexCollectionGetResponse]
            The index resource was returned successfully.  You will receive a JSON object detailing the
            organization of books, chapters, and verse counts for the requested Bible version.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/index",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesIndexCollectionGetResponse,
                    parse_obj_as(
                        type_=BiblesIndexCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def passages_resource_get(
        self,
        bible_id_path: int,
        passage_id_path: str,
        *,
        format: typing.Optional[BiblesPassagesResourceGetRequestFormat] = None,
        include_headings: typing.Optional[bool] = None,
        include_notes: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BiblesPassagesResourceGetResponse]:
        """
        Returns the specified scripture passage in the requested format. Headings and
        notes may be included via query parameters, but only when format=html. They
        are omitted when format=text. The response includes content text and metadata
        such as verse ranges and formatting details.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        passage_id_path : str
            The passage identifier (verse or chapter USFM format)

        format : typing.Optional[BiblesPassagesResourceGetRequestFormat]
            The desired Bible content format (text or html). Headings and notes are included only when format=html; format=text returns verse text without them.

        include_headings : typing.Optional[bool]
            Whether or not headings should be included in the Bible content. Headings are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.

        include_notes : typing.Optional[bool]
            Whether or not notes should be included in the Bible content. Notes are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesPassagesResourceGetResponse]
            The passage was retrieved successfully in the desired format. The response
            body contains a JSON object with verse text and formatting metadata.
            Optional headings and notes are present only when format=html.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/passages/{encode_path_param(passage_id_path)}",
            method="GET",
            params={
                "format": format,
                "include_headings": include_headings,
                "include_notes": include_notes,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesPassagesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesPassagesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_collection_get(
        self,
        bible_id_path: int,
        *,
        canon: typing.Optional[BiblesBooksCollectionGetRequestCanon] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Optional[BiblesBooksCollectionGetResponse]]:
        """
        Retrieves the list of books (e.g. Genesis, Exodus) for the specified Bible version.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        canon : typing.Optional[BiblesBooksCollectionGetRequestCanon]
            The Canon to filter results by

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[BiblesBooksCollectionGetResponse]]
            The collection of books was returned successfully.  The JSON array in the response body details
            book identifiers, names, and order within the Bible version.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books",
            method="GET",
            params={
                "canon": canon,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_resource_get(
        self, bible_id_path: int, book_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[BiblesBooksResourceGetResponse]:
        """
        Get a Book resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesBooksResourceGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_chapters_collection_get(
        self, bible_id_path: int, book_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[BiblesBooksChaptersCollectionGetResponse]]:
        """
        Get a collection of Chapters for the given Bible and Book

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[BiblesBooksChaptersCollectionGetResponse]]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksChaptersCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksChaptersCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_chapters_resource_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BiblesBooksChaptersResourceGetResponse]:
        """
        Get a Chapter resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesBooksChaptersResourceGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksChaptersResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksChaptersResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_chapters_verses_collection_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse]]:
        """
        Get a collection of Verses for a Chapter.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse]]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}/verses",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[BiblesBooksChaptersVersesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def books_chapters_verses_resource_get(
        self,
        bible_id_path: int,
        book_id: str,
        chapter_id: str,
        verse_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BiblesBooksChaptersVersesResourceGetResponse]:
        """
        Get a Verse resource. This does not include the text content; use the Passages endpoint for that.

        Parameters
        ----------
        bible_id_path : int
            The Bible version identifier

        book_id : str
            The Bible Book identifier which is commonly the first 3 characters of the USFM reference

        chapter_id : str
            The Bible Chapter identifier which is part of the USFM reference.

        verse_id : str
            The Bible Verse identifier pulled from part of the USFM reference

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BiblesBooksChaptersVersesResourceGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/bibles/{encode_path_param(bible_id_path)}/books/{encode_path_param(book_id)}/chapters/{encode_path_param(chapter_id)}/verses/{encode_path_param(verse_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BiblesBooksChaptersVersesResourceGetResponse,
                    parse_obj_as(
                        type_=BiblesBooksChaptersVersesResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
