// Code generated by Fern. DO NOT EDIT.

// Provides data about Bible versions and their content.  Use these endpoints to get passage text,
// as well as metadata about available Bibles and their structure.
package bibles
