// Code generated by Fern. DO NOT EDIT.

package dataexchange

import (
	context "context"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the browser-rendered data exchange approval page for a short-lived token. The app
// should first create a token with `POST /data-exchange/token`, then open this URL in the
// user's browser with the token and app context. The page lets the user review the requested
// permissions before approving or cancelling the exchange.
func (c *Client) ApprovalGet(
	ctx context.Context,
	request *platform.DataExchangeApprovalGetRequest,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.ApprovalGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Completes the browser approval flow and redirects the browser to the app's configured
// callback URL. When approval succeeds, the callback receives
// `data_exchange_status=granted` and `granted_permissions`. When the user cancels from the
// approval page, the callback receives `data_exchange_status=cancelled`,
// `denied_permissions`, and `error=access_denied`. Recoverable errors after a safe callback
// is known redirect with `data_exchange_status=error`, `error`, and `error_description`.
func (c *Client) ApprovalPost(
	ctx context.Context,
	request *platform.DataExchangeApprovalPostRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ApprovalPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Creates a short-lived token that can be passed to the `/data-exchange` browser flow as a
// query parameter. Send `requested_permissions` in the request body to declare which
// permissions the user should review during the browser flow. Tokens expire after five minutes
// and are consumed when the form is submitted.
func (c *Client) TokenPost(
	ctx context.Context,
	request *platform.DataExchangeTokenPostRequest,
	opts ...option.RequestOption,
) (*platform.DataExchangeTokenPostResponse, error) {
	response, err := c.WithRawResponse.TokenPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
