// Code generated by Fern. DO NOT EDIT.

package verseofthedays

import (
	context "context"
	http "net/http"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) V1VerseOfTheDaysCanonicalCollectionGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*platform.V1VerseOfTheDaysCanonicalCollectionGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := baseURL + "/v1/verse-of-the-days"
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	var response *platform.V1VerseOfTheDaysCanonicalCollectionGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:                endpointURL,
			Method:             http.MethodGet,
			Headers:            headers,
			MaxAttempts:        options.MaxAttempts,
			DisableRetries:     options.DisableRetries,
			BodyProperties:     options.BodyProperties,
			QueryParameters:    options.QueryParameters,
			Client:             options.HTTPClient,
			Response:           &response,
			ResponseIsOptional: true,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*platform.V1VerseOfTheDaysCanonicalCollectionGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) V1VerseOfTheDaysCanonicalResourceGet(
	ctx context.Context,
	request *platform.V1VerseOfTheDaysCanonicalResourceGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*platform.V1VerseOfTheDaysCanonicalResourceGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/verse-of-the-days/%v",
		request.Day,
	)
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	var response *platform.V1VerseOfTheDaysCanonicalResourceGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*platform.V1VerseOfTheDaysCanonicalResourceGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
