// Generated by scripts/generate-cli.mjs. Do not edit.
import type { YouVersionPlatformClient } from '@cameronapak/platform-sdk';
import type { Operation } from './operation.js';

const metadata: Omit<Operation, 'execute'>[] = [
  {
    "operationId": "bibles.collection_get",
    "command": [
      "bibles",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles",
    "description": "Get a Bible collection\nRetrieves a paginated list of Bible versions available.\nWhen multiple language_ranges parameters are specified, the set of Bibles returned will be from\nthe first language range which has available Bibles.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "all_available",
        "flag": "all-available",
        "location": "query",
        "required": false,
        "description": "This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.",
        "schema": {
          "type": "boolean"
        }
      },
      {
        "name": "language_ranges[]",
        "flag": "language-ranges",
        "location": "query",
        "required": true,
        "description": "An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2\nLanguage ranges in this parameter may only be of the Basic Range format.",
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([A-z]{1,8}([-_][0-9A-z]{1,8})*)$|^\\*$"
          }
        }
      },
      {
        "name": "license_id",
        "flag": "license-id",
        "location": "query",
        "required": false,
        "description": "Filter Bibles by a license identifier",
        "schema": {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "page_size",
        "flag": "page-size",
        "location": "query",
        "required": false,
        "description": "The number of items to return in the collection.  Numeric values must be between 1 and 99.\nSpecial value \"*\" is supported only when used in combination with the `fields` parameter and\nwhen the client requests three or fewer fields (see `fields` parameter). When \"*\" is used the\nserver will return all matching items for the requested resource (no numeric page limit).\n",
        "schema": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 99
            },
            {
              "type": "string",
              "enum": [
                "*"
              ]
            }
          ]
        }
      },
      {
        "name": "fields[]",
        "flag": "fields",
        "location": "query",
        "required": false,
        "description": "A list of top-level fields to include in each resource object. Use bracket notation to pass\nmultiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.\nWhen provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.\n",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      {
        "name": "page_token",
        "flag": "page-token",
        "location": "query",
        "required": false,
        "description": "The page token to retrieve results from.",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "bibles.resource_get",
    "command": [
      "bibles",
      "resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}",
    "description": "Get a Bible's data\nGet a Bible resource for a single Bible version.\nThis does not include the Bible's text content; use the Passages endpoint for that.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "bibles_books.collection_get",
    "command": [
      "bibles",
      "books-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books",
    "description": "Get a Book collection for a Bible\nRetrieves the list of books (e.g. Genesis, Exodus) for the specified Bible version.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "canon",
        "flag": "canon",
        "location": "query",
        "required": false,
        "description": "The Canon to filter results by",
        "schema": {
          "enum": [
            "new_testament",
            "old_testament",
            "deuterocanon"
          ],
          "type": "string"
        }
      },
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "bibles_books.resource_get",
    "command": [
      "bibles",
      "books-resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books/{book_id}",
    "description": "Get a Book's data\nGet a Book resource. This does not include the text content; use the Passages endpoint for that.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "book_id",
        "flag": "book-id",
        "location": "path",
        "required": true,
        "description": "The Bible Book identifier which is commonly the first 3 characters of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        }
      }
    ]
  },
  {
    "operationId": "bibles_books_chapters.collection_get",
    "command": [
      "bibles",
      "books-chapters-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books/{book_id}/chapters",
    "description": "Get a Chapter collection for a Book\nGet a collection of Chapters for the given Bible and Book",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "book_id",
        "flag": "book-id",
        "location": "path",
        "required": true,
        "description": "The Bible Book identifier which is commonly the first 3 characters of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        }
      }
    ]
  },
  {
    "operationId": "bibles_books_chapters.resource_get",
    "command": [
      "bibles",
      "books-chapters-resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}",
    "description": "Get a Chapter's data\nGet a Chapter resource. This does not include the text content; use the Passages endpoint for that.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "book_id",
        "flag": "book-id",
        "location": "path",
        "required": true,
        "description": "The Bible Book identifier which is commonly the first 3 characters of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        }
      },
      {
        "name": "chapter_id",
        "flag": "chapter-id",
        "location": "path",
        "required": true,
        "description": "The Bible Chapter identifier which is part of the USFM reference.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 7
        }
      }
    ]
  },
  {
    "operationId": "bibles_books_chapters_verses.collection_get",
    "command": [
      "bibles",
      "books-chapters-verses-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}/verses",
    "description": "Get a Verse collection for a Chapter\nGet a collection of Verses for a Chapter.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "book_id",
        "flag": "book-id",
        "location": "path",
        "required": true,
        "description": "The Bible Book identifier which is commonly the first 3 characters of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        }
      },
      {
        "name": "chapter_id",
        "flag": "chapter-id",
        "location": "path",
        "required": true,
        "description": "The Bible Chapter identifier which is part of the USFM reference.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 7
        }
      }
    ]
  },
  {
    "operationId": "bibles_books_chapters_verses.resource_get",
    "command": [
      "bibles",
      "books-chapters-verses-resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}/verses/{verse_id}",
    "description": "Get a Verse's data\nGet a Verse resource. This does not include the text content; use the Passages endpoint for that.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "book_id",
        "flag": "book-id",
        "location": "path",
        "required": true,
        "description": "The Bible Book identifier which is commonly the first 3 characters of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        }
      },
      {
        "name": "chapter_id",
        "flag": "chapter-id",
        "location": "path",
        "required": true,
        "description": "The Bible Chapter identifier which is part of the USFM reference.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 7
        }
      },
      {
        "name": "verse_id",
        "flag": "verse-id",
        "location": "path",
        "required": true,
        "description": "The Bible Verse identifier pulled from part of the USFM reference",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 7
        }
      }
    ]
  },
  {
    "operationId": "bibles_index.collection_get",
    "command": [
      "bibles",
      "index-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/index",
    "description": "Get the index for a Bible\nRetrieves the indexing structure for the specified Bible version.  This includes the full hierarchy of\nbooks, chapters, and verse counts.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "bibles_passages.resource_get",
    "command": [
      "bibles",
      "passages-resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/bibles/{bible_id_path}/passages/{passage_id_path}",
    "description": "Get a passage of Bible text\nReturns the specified scripture passage in the requested format. Headings and\nnotes may be included via query parameters, but only when format=html. They\nare omitted when format=text. The response includes content text and metadata\nsuch as verse ranges and formatting details.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "format",
        "flag": "format",
        "location": "query",
        "required": false,
        "description": "The desired Bible content format (text or html). Headings and notes are included only when format=html; format=text returns verse text without them.",
        "schema": {
          "type": "string",
          "enum": [
            "text",
            "html"
          ]
        }
      },
      {
        "name": "include_headings",
        "flag": "include-headings",
        "location": "query",
        "required": false,
        "description": "Whether or not headings should be included in the Bible content. Headings are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.",
        "schema": {
          "type": "boolean"
        }
      },
      {
        "name": "include_notes",
        "flag": "include-notes",
        "location": "query",
        "required": false,
        "description": "Whether or not notes should be included in the Bible content. Notes are returned only when format=html; they are omitted when format=text. The default for this field is false unless the reference is a chapter or introduction (GEN.1 or GEN.INTRO1) in which case it would be true.",
        "schema": {
          "type": "boolean"
        }
      },
      {
        "name": "passage_id_path",
        "flag": "passage-id-path",
        "location": "path",
        "required": true,
        "description": "The passage identifier (verse or chapter USFM format)",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "bible_id_path",
        "flag": "bible-id-path",
        "location": "path",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "data_exchange.approval_get",
    "command": [
      "data-exchange",
      "approval-get"
    ],
    "httpMethod": "GET",
    "path": "/data-exchange",
    "description": "Show the data exchange approval page.\nReturns the browser-rendered data exchange approval page for a short-lived token. The app\nshould first create a token with `POST /data-exchange/token`, then open this URL in the\nuser's browser with the token and app context. The page lets the user review the requested\npermissions before approving or cancelling the exchange.\n",
    "kind": "read",
    "auth": "exchange-token",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "text",
    "redirect": true,
    "inputs": [
      {
        "name": "token",
        "flag": "token",
        "location": "query",
        "required": true,
        "description": "Short-lived data exchange token created by `POST /data-exchange/token`.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_DATA_EXCHANGE_TOKEN"
      },
      {
        "name": "x-yvp-app-key",
        "flag": "x-yvp-app-key",
        "location": "query",
        "required": false,
        "description": "Public app key used to resolve the app for direct browser flows.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_DATA_EXCHANGE_APP_KEY"
      },
      {
        "name": "x-yvp-app-id",
        "flag": "x-yvp-app-id",
        "location": "query",
        "required": false,
        "description": "App identifier used when a public app key is not supplied.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    ]
  },
  {
    "operationId": "data_exchange.approval_post",
    "command": [
      "data-exchange",
      "approval-post"
    ],
    "httpMethod": "POST",
    "path": "/data-exchange",
    "description": "Complete the data exchange approval flow.\nCompletes the browser approval flow and redirects the browser to the app's configured\ncallback URL. When approval succeeds, the callback receives\n`data_exchange_status=granted` and `granted_permissions`. When the user cancels from the\napproval page, the callback receives `data_exchange_status=cancelled`,\n`denied_permissions`, and `error=access_denied`. Recoverable errors after a safe callback\nis known redirect with `data_exchange_status=error`, `error`, and `error_description`.\n",
    "kind": "write",
    "auth": "approval",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "empty",
    "redirect": true,
    "inputs": [
      {
        "name": "token",
        "flag": "token",
        "location": "query",
        "required": false,
        "description": "Short-lived data exchange token created by `POST /data-exchange/token`.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_DATA_EXCHANGE_TOKEN"
      },
      {
        "name": "x-yvp-app-key",
        "flag": "x-yvp-app-key",
        "location": "query",
        "required": false,
        "description": "Public app key used to resolve the app when a token is not supplied.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_DATA_EXCHANGE_APP_KEY"
      },
      {
        "name": "x-yvp-app-id",
        "flag": "x-yvp-app-id",
        "location": "query",
        "required": false,
        "description": "App identifier used when a public app key is not supplied.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      },
      {
        "name": "Authorization",
        "flag": "authorization",
        "location": "header",
        "required": false,
        "description": "Bearer access token used only by clients that complete the flow without a token.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_ACCESS_TOKEN"
      }
    ]
  },
  {
    "operationId": "data_exchange.token_post",
    "command": [
      "data-exchange",
      "token-post"
    ],
    "httpMethod": "POST",
    "path": "/data-exchange/token",
    "description": "Create a data exchange token.\nCreates a short-lived token that can be passed to the `/data-exchange` browser flow as a\nquery parameter. Send `requested_permissions` in the request body to declare which\npermissions the user should review during the browser flow. Tokens expire after five minutes\nand are consumed when the form is submitted.\n",
    "kind": "write",
    "auth": "oauth",
    "sensitive": true,
    "requiresDisclosure": true,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "Authorization",
        "flag": "authorization",
        "location": "header",
        "required": true,
        "description": "Bearer access token for the authenticated user.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_ACCESS_TOKEN"
      },
      {
        "name": "x-yvp-app-key",
        "flag": "x-yvp-app-key",
        "location": "query",
        "required": false,
        "description": "Public app key used to resolve the app for direct browser flows.",
        "schema": {
          "type": "string"
        },
        "secretEnv": "YOUVERSION_DATA_EXCHANGE_APP_KEY"
      },
      {
        "name": "x-yvp-app-id",
        "flag": "x-yvp-app-id",
        "location": "query",
        "required": false,
        "description": "App identifier used when a public app key is not supplied.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    ],
    "body": {
      "type": "object",
      "properties": {
        "requested_permissions": {
          "description": "Data exchange permissions the user should review in the browser flow.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "highlights"
            ]
          }
        }
      },
      "required": [
        "requested_permissions"
      ],
      "additionalProperties": false
    }
  },
  {
    "operationId": "v1.apps.permissions.collection_get",
    "command": [
      "permissions",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/apps/{app_id}/permissions",
    "description": "Get permissions granted to an app.\nReturns permissions the authenticated user has already granted to the calling app. Use this\nendpoint before starting an OAuth permission request when you need to know whether the user\nhas already granted access. The app ID path parameter must match the gateway-injected\ncalling app ID. An empty permissions array means the user has not granted permissions for\nthis app.\n",
    "kind": "read",
    "auth": "oauth",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "app_id",
        "flag": "app-id",
        "location": "path",
        "required": true,
        "description": "The unique identifier of the app.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    ]
  },
  {
    "operationId": "v1.apps.resource_get",
    "command": [
      "apps",
      "resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/apps/{app_id}",
    "description": "Get details about a specific app in the Platform.\nGet a single app resource by its id.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "app_id",
        "flag": "app-id",
        "location": "path",
        "required": true,
        "description": "The unique identifier of the app.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    ]
  },
  {
    "operationId": "v1.fonts.collection_get",
    "command": [
      "fonts",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/fonts",
    "description": "Get a collection of fonts supported in the Platform.\nGet a collection of font family resources with their available variants and CDN sources.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": []
  },
  {
    "operationId": "v1.fonts.resource_get",
    "command": [
      "fonts",
      "resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/fonts/{font_id}",
    "description": "Get details about a specific font family in the Platform.\nGet a single font family resource by its integer identifier.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "font_id",
        "flag": "font-id",
        "location": "path",
        "required": true,
        "description": "The unique integer identifier for a font family resource in the Platform.",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "v1.fonts.stylesheet_get",
    "command": [
      "fonts",
      "stylesheet-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/fonts/{font_id}/stylesheet",
    "description": "Get a browser-consumable stylesheet for a specific font family.\nGet a text/css stylesheet for a single font family resource using the canonical woff2 CDN URLs exposed by the JSON Fonts API for browser consumption. The API gateway accepts `app_key` on this route and injects the required app-id header before forwarding the request to this service.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "text",
    "redirect": false,
    "inputs": [
      {
        "name": "font_id",
        "flag": "font-id",
        "location": "path",
        "required": true,
        "description": "The unique integer identifier for a font family resource in the Platform.",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      }
    ]
  },
  {
    "operationId": "v1.highlights.collection_get",
    "command": [
      "highlights",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/highlights",
    "description": "Get a collection of highlights for a user.\nThe response will return a color per verse without ranges.",
    "kind": "read",
    "auth": "oauth",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id",
        "flag": "bible-id",
        "location": "query",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "passage_id",
        "flag": "passage-id",
        "location": "query",
        "required": true,
        "description": "The passage identifier (verse or chapter USFM format)",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.highlights.collection_post",
    "command": [
      "highlights",
      "collection-post"
    ],
    "httpMethod": "POST",
    "path": "/v1/highlights",
    "description": "Create or update a highlight on a passage.\nVerse ranges may be used in the POST body passage_id attribute.",
    "kind": "write",
    "auth": "oauth",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [],
    "body": {
      "type": "object",
      "properties": {
        "request_id": {
          "description": "Request UUID for idempotent create retries.",
          "type": "string",
          "format": "uuid"
        },
        "highlight": {
          "type": "object",
          "properties": {
            "bible_id": {
              "description": "Bible version identifier",
              "type": "integer",
              "format": "int32",
              "minimum": -9007199254740991,
              "maximum": 9007199254740991
            },
            "passage_id": {
              "description": "The passage identifier (verse USFM format)",
              "type": "string"
            },
            "color": {
              "description": "The highlight color in hex format",
              "type": "string",
              "pattern": "^[0-9a-f]{6}$"
            }
          },
          "required": [
            "bible_id",
            "passage_id",
            "color"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "request_id",
        "highlight"
      ],
      "additionalProperties": false
    }
  },
  {
    "operationId": "v1.highlights.resource_delete",
    "command": [
      "highlights",
      "resource-delete"
    ],
    "httpMethod": "DELETE",
    "path": "/v1/highlights/{passage_id_path}",
    "description": "Clear highlights for a passage.\nClear highlights for a passage.",
    "kind": "write",
    "auth": "oauth",
    "sensitive": true,
    "requiresDisclosure": false,
    "response": "empty",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id",
        "flag": "bible-id",
        "location": "query",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "passage_id_path",
        "flag": "passage-id-path",
        "location": "path",
        "required": true,
        "description": "The passage identifier (verse or chapter USFM format)",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.languages.collection_get",
    "command": [
      "languages",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/languages",
    "description": "Get a collection of languages supported in the Platform.\nGet a collection of language objects. Add the Country parameter to filter to prominent languages for that country. Send an Accept-Language header to control which name is returned in each language's localized_name; the negotiated locale is echoed in the Content-Language response header. Each object's display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names (and use page_size) when you only need localized_name.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "Accept-Language",
        "flag": "accept-language",
        "location": "header",
        "required": false,
        "description": "The localization preferred as a response to the request. See RFC 2616 section 14.4 for further details.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "page_size",
        "flag": "page-size",
        "location": "query",
        "required": false,
        "description": "The number of items to return in the collection.  Numeric values must be between 1 and 99.\nSpecial value \"*\" is supported only when used in combination with the `fields` parameter and\nwhen the client requests three or fewer fields (see `fields` parameter). When \"*\" is used the\nserver will return all matching items for the requested resource (no numeric page limit).\n",
        "schema": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 99
            },
            {
              "type": "string",
              "enum": [
                "*"
              ]
            }
          ]
        }
      },
      {
        "name": "fields[]",
        "flag": "fields",
        "location": "query",
        "required": false,
        "description": "A list of top-level fields to include in each resource object. Use bracket notation to pass\nmultiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.\nWhen provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.\n",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      {
        "name": "page_token",
        "flag": "page-token",
        "location": "query",
        "required": false,
        "description": "The page token to retrieve results from.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "country",
        "flag": "country",
        "location": "query",
        "required": false,
        "description": "The ISO 3166 2 character country code",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "bibles_available",
        "flag": "bibles-available",
        "location": "query",
        "required": false,
        "description": "Filter languages based on whether Bible content is available for that language.",
        "schema": {
          "type": "boolean"
        }
      }
    ]
  },
  {
    "operationId": "v1.languages.resource_get",
    "command": [
      "languages",
      "resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/languages/{language_id}",
    "description": "Get details about a specific language in the Platform.\nGet a single language resource by its BCP47 language code. Send an Accept-Language header to control which name is returned in localized_name; the negotiated locale is echoed in the Content-Language response header. The display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names when you only need localized_name.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "Accept-Language",
        "flag": "accept-language",
        "location": "header",
        "required": false,
        "description": "The localization preferred as a response to the request. See RFC 2616 section 14.4 for further details.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "language_id",
        "flag": "language-id",
        "location": "path",
        "required": true,
        "description": "The language identifier uses the canonical BCP 47 language code, optionally including the script subtag when it distinguishes writing systems (for example, sr-Latn vs sr-Cyrl). Region subtags are excluded because they usually represent contextual or user-specific preferences rather than the intrinsic identity of the language, with one exception: a small, enumerated set of region variants that speakers treat as distinct languages is preserved (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Every other region, plus variants and extensions, is excluded, and a request for one redirects to the canonical region-agnostic id. This keeps identifiers stable and minimal while still surfacing the variants users distinguish.",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.licenses.collection_get",
    "command": [
      "licenses",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/licenses",
    "description": "Get a collection of licenses\nReturns a list of license metadata. By default, the response returns all licenses.\nIn the case that `developer_id` is passed in the query, it filters to only include licenses\nthe developer has agreed to. In the case that `bible_id` is passed it only returns the\nlicense under which that Bible ID is currently licensed. The license object also contains\na list of all Bible ids are offered under that license.\nOptionally combine `developer_id` with the `all_available` query parameter to receive\nevery license while still surfacing the developer's agreement metadata when present.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "bible_id",
        "flag": "bible-id",
        "location": "query",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "developer_id",
        "flag": "developer-id",
        "location": "query",
        "required": true,
        "description": "The Developer's unique ID in the Platform.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      },
      {
        "name": "all_available",
        "flag": "all-available",
        "location": "query",
        "required": false,
        "description": "This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.",
        "schema": {
          "type": "boolean"
        }
      }
    ]
  },
  {
    "operationId": "v1.organizations.bibles.collection_get",
    "command": [
      "organizations",
      "bibles-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/organizations/{organization_id}/bibles",
    "description": "Get bibles associated with a specific organization in the Platform.\nGet bibles associated with a specific organization by its id.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "organization_id",
        "flag": "organization-id",
        "location": "path",
        "required": true,
        "description": "The Organization unique ID provided in the Platform.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      },
      {
        "name": "page_size",
        "flag": "page-size",
        "location": "query",
        "required": false,
        "description": "The number of items to return in the collection.  Numeric values must be between 1 and 99.\nSpecial value \"*\" is supported only when used in combination with the `fields` parameter and\nwhen the client requests three or fewer fields (see `fields` parameter). When \"*\" is used the\nserver will return all matching items for the requested resource (no numeric page limit).\n",
        "schema": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 99
            },
            {
              "type": "string",
              "enum": [
                "*"
              ]
            }
          ]
        }
      },
      {
        "name": "fields[]",
        "flag": "fields",
        "location": "query",
        "required": false,
        "description": "A list of top-level fields to include in each resource object. Use bracket notation to pass\nmultiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.\nWhen provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.\n",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      {
        "name": "page_token",
        "flag": "page-token",
        "location": "query",
        "required": false,
        "description": "The page token to retrieve results from.",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.organizations.collection_get",
    "command": [
      "organizations",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/organizations",
    "description": "Get a collection of organizations in the Platform.\nReturns a paginated list of Organization objects. Use bible_ids[] to filter\nto organizations associated with the given Bible version(s); when omitted,\nall organizations are returned.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "Accept-Language",
        "flag": "accept-language",
        "location": "header",
        "required": false,
        "description": "The localization preferred as a response to the request. See RFC 2616 section 14.4 for further details.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "bible_ids[]",
        "flag": "bible-ids",
        "location": "query",
        "required": false,
        "description": "Filter organizations to those associated with the given Bible version(s). Use bracket notation: bible_ids[]=111&bible_ids[]=206. When omitted, returns all organizations.",
        "schema": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        }
      },
      {
        "name": "page_size",
        "flag": "page-size",
        "location": "query",
        "required": false,
        "description": "The number of items to return in the collection.  Numeric values must be between 1 and 99.\nSpecial value \"*\" is supported only when used in combination with the `fields` parameter and\nwhen the client requests three or fewer fields (see `fields` parameter). When \"*\" is used the\nserver will return all matching items for the requested resource (no numeric page limit).\n",
        "schema": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 99
            },
            {
              "type": "string",
              "enum": [
                "*"
              ]
            }
          ]
        }
      },
      {
        "name": "fields[]",
        "flag": "fields",
        "location": "query",
        "required": false,
        "description": "A list of top-level fields to include in each resource object. Use bracket notation to pass\nmultiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.\nWhen provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.\n",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      {
        "name": "page_token",
        "flag": "page-token",
        "location": "query",
        "required": false,
        "description": "The page token to retrieve results from.",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.organizations.resource_get",
    "command": [
      "organizations",
      "resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/organizations/{organization_id}",
    "description": "Get details about a specific organization in the Platform.\nGet a single organization resource by its id.",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "Accept-Language",
        "flag": "accept-language",
        "location": "header",
        "required": false,
        "description": "The localization preferred as a response to the request. See RFC 2616 section 14.4 for further details.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "organization_id",
        "flag": "organization-id",
        "location": "path",
        "required": true,
        "description": "The Organization unique ID provided in the Platform.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    ]
  },
  {
    "operationId": "v1.search_queries.collection_get",
    "command": [
      "search-queries",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/search-queries",
    "description": "Get suggested or trending search queries.\nReturns query objects (a search string and its source). Supply query with language_ranges[] for as-you-type suggestions, or trending=true with language_ranges[] for recently popular searches. When trending=true, query is ignored. The first language range supported by search is used.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "language_ranges[]",
        "flag": "language-ranges",
        "location": "query",
        "required": true,
        "description": "An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2\nLanguage ranges in this parameter may only be of the Basic Range format.",
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([A-z]{1,8}([-_][0-9A-z]{1,8})*)$|^\\*$"
          }
        }
      },
      {
        "name": "query",
        "flag": "query",
        "location": "query",
        "required": false,
        "description": "The partial query for as-you-type suggestions. Omit for trending queries.",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "trending",
        "flag": "trending",
        "location": "query",
        "required": false,
        "description": "Return recently popular searches for the language instead of suggestions.",
        "schema": {
          "type": "boolean"
        }
      }
    ]
  },
  {
    "operationId": "v1.search_topics.collection_get",
    "command": [
      "search-topics",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/search-topics",
    "description": "Search the Platform for topics related to a query.\nReturns the set of topics (id, text, subtopics) related to a query, for pivoting to other verses in the same topic.\n\nThis endpoint is unpaginated: Core Search returns a fixed set of topics and exposes no page_size or page_token parameters. Query metadata (did_you_mean, search_instead_for) is always included.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "query",
        "flag": "query",
        "location": "query",
        "required": true,
        "description": "The search query string used to find matching results.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      },
      {
        "name": "language_ranges[]",
        "flag": "language-ranges",
        "location": "query",
        "required": true,
        "description": "An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2\nLanguage ranges in this parameter may only be of the Basic Range format.",
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([A-z]{1,8}([-_][0-9A-z]{1,8})*)$|^\\*$"
          }
        }
      }
    ]
  },
  {
    "operationId": "v1.search_unified.collection_get",
    "command": [
      "search-unified",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/search-unified",
    "description": "Search the Platform for Bible verses and related topics.\nSearch for Bible verses and related topics by query, returning a single unified set of results across all content kinds. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint.\n\nThis endpoint is unpaginated: it returns one combined page of top results per kind and exposes no page_size or page_token parameters. Use the kind-specific endpoints (search-verses, search-topics) when you need to page through the full result set for a single kind.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "query",
        "flag": "query",
        "location": "query",
        "required": true,
        "description": "The search query string used to find matching results.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      },
      {
        "name": "bible_id",
        "flag": "bible-id",
        "location": "query",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "language_ranges[]",
        "flag": "language-ranges",
        "location": "query",
        "required": true,
        "description": "An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2\nLanguage ranges in this parameter may only be of the Basic Range format.",
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([A-z]{1,8}([-_][0-9A-z]{1,8})*)$|^\\*$"
          }
        }
      },
      {
        "name": "user_intent",
        "flag": "user-intent",
        "location": "query",
        "required": false,
        "description": "The searcher's intent. Defaults to unknown, matching the Core Search service.",
        "schema": {
          "type": "string",
          "enum": [
            "unknown",
            "topical",
            "text",
            "reference"
          ]
        }
      },
      {
        "name": "fields[]",
        "flag": "fields",
        "location": "query",
        "required": false,
        "description": "Result kinds to include: `verses` and/or `topics`. Use bracket notation to pass multiple\nvalues, for example `fields[]=verses&fields[]=topics`. Omit to return all kinds. Query\nmetadata is always included.\n",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    ]
  },
  {
    "operationId": "v1.search_verses.collection_get",
    "command": [
      "search-verses",
      "collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/search-verses",
    "description": "Search the Platform for Bible verses.\nSearch for Bible verses by query, returning a paginated list of verse references. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint. The bible_id determines the language searched, so this endpoint takes no language parameter. Use page_size and page_token to page through the full result set.\n",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "query",
        "flag": "query",
        "location": "query",
        "required": true,
        "description": "The search query string used to find matching results.",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      },
      {
        "name": "bible_id",
        "flag": "bible-id",
        "location": "query",
        "required": true,
        "description": "The Bible version identifier",
        "schema": {
          "type": "integer",
          "format": "int32",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        }
      },
      {
        "name": "user_intent",
        "flag": "user-intent",
        "location": "query",
        "required": false,
        "description": "The searcher's intent. Defaults to unknown, matching the Core Search service.",
        "schema": {
          "type": "string",
          "enum": [
            "unknown",
            "topical",
            "text",
            "reference"
          ]
        }
      },
      {
        "name": "page_size",
        "flag": "page-size",
        "location": "query",
        "required": false,
        "description": "The number of verse results to return in the collection. Must be between 1 and 99.",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 99
        }
      },
      {
        "name": "page_token",
        "flag": "page-token",
        "location": "query",
        "required": false,
        "description": "The page token to retrieve results from.",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
  {
    "operationId": "v1.verse_of_the_days.canonical.collection_get",
    "command": [
      "verse-of-the-days",
      "canonical-collection-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/verse-of-the-days",
    "description": "Get the verse of the day calendar for an entire year.\nJanuary 1 is day 1 and December 31 is day 365 (or 366 in a leap year).",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": []
  },
  {
    "operationId": "v1.verse_of_the_days.canonical.resource_get",
    "command": [
      "verse-of-the-days",
      "canonical-resource-get"
    ],
    "httpMethod": "GET",
    "path": "/v1/verse-of-the-days/{day}",
    "description": "Get the verse of the day for a specific day of the year.\nDay is the day of the year (1-366).",
    "kind": "read",
    "auth": "app-key",
    "sensitive": false,
    "requiresDisclosure": false,
    "response": "json",
    "redirect": false,
    "inputs": [
      {
        "name": "day",
        "flag": "day",
        "location": "path",
        "required": true,
        "description": "The day of the year (1-366)",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 366
        }
      }
    ]
  }
];

export const operations: Operation[] = [
  { ...metadata[0], execute: (client, request, options) => client.bibles.collectionGet({ "all_available": request["all_available"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["all_available"], "language_ranges[]": request["language_ranges[]"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["language_ranges[]"], "license_id": request["license_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["license_id"], "page_size": request["page_size"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["page_size"], "fields[]": request["fields[]"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["fields[]"], "page_token": request["page_token"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>["page_token"] }, options).withRawResponse() },
  { ...metadata[1], execute: (client, request, options) => client.bibles.resourceGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["resourceGet"]>[0]>["bible_id_path"] }, options).withRawResponse() },
  { ...metadata[2], execute: (client, request, options) => client.bibles.booksCollectionGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksCollectionGet"]>[0]>["bible_id_path"], "canon": request["canon"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksCollectionGet"]>[0]>["canon"] }, options).withRawResponse() },
  { ...metadata[3], execute: (client, request, options) => client.bibles.booksResourceGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksResourceGet"]>[0]>["bible_id_path"], "book_id": request["book_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksResourceGet"]>[0]>["book_id"] }, options).withRawResponse() },
  { ...metadata[4], execute: (client, request, options) => client.bibles.booksChaptersCollectionGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersCollectionGet"]>[0]>["bible_id_path"], "book_id": request["book_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersCollectionGet"]>[0]>["book_id"] }, options).withRawResponse() },
  { ...metadata[5], execute: (client, request, options) => client.bibles.booksChaptersResourceGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>[0]>["bible_id_path"], "book_id": request["book_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>[0]>["book_id"], "chapter_id": request["chapter_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>[0]>["chapter_id"] }, options).withRawResponse() },
  { ...metadata[6], execute: (client, request, options) => client.bibles.booksChaptersVersesCollectionGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>[0]>["bible_id_path"], "book_id": request["book_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>[0]>["book_id"], "chapter_id": request["chapter_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>[0]>["chapter_id"] }, options).withRawResponse() },
  { ...metadata[7], execute: (client, request, options) => client.bibles.booksChaptersVersesResourceGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>[0]>["bible_id_path"], "book_id": request["book_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>[0]>["book_id"], "chapter_id": request["chapter_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>[0]>["chapter_id"], "verse_id": request["verse_id"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>[0]>["verse_id"] }, options).withRawResponse() },
  { ...metadata[8], execute: (client, request, options) => client.bibles.indexCollectionGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["indexCollectionGet"]>[0]>["bible_id_path"] }, options).withRawResponse() },
  { ...metadata[9], execute: (client, request, options) => client.bibles.passagesResourceGet({ "bible_id_path": request["bible_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>["bible_id_path"], "passage_id_path": request["passage_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>["passage_id_path"], "format": request["format"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>["format"], "include_headings": request["include_headings"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>["include_headings"], "include_notes": request["include_notes"] as NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>["include_notes"] }, options).withRawResponse() },
  { ...metadata[10], execute: (client, request, options) => client.dataExchange.approvalGet({ "token": request["token"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalGet"]>[0]>["token"], "x-yvp-app-key": request["x-yvp-app-key"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalGet"]>[0]>["x-yvp-app-key"], "x-yvp-app-id": request["x-yvp-app-id"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalGet"]>[0]>["x-yvp-app-id"] }, options).withRawResponse() },
  { ...metadata[11], execute: (client, request, options) => client.dataExchange.approvalPost({ "token": request["token"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalPost"]>[0]>["token"], "x-yvp-app-key": request["x-yvp-app-key"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalPost"]>[0]>["x-yvp-app-key"], "x-yvp-app-id": request["x-yvp-app-id"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["approvalPost"]>[0]>["x-yvp-app-id"] }, options).withRawResponse() },
  { ...metadata[12], execute: (client, request, options) => client.dataExchange.tokenPost({ "x-yvp-app-key": request["x-yvp-app-key"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["tokenPost"]>[0]>["x-yvp-app-key"], "x-yvp-app-id": request["x-yvp-app-id"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["tokenPost"]>[0]>["x-yvp-app-id"], "requested_permissions": request["requested_permissions"] as NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["tokenPost"]>[0]>["requested_permissions"] }, options).withRawResponse() },
  { ...metadata[13], execute: (client, request, options) => client.permissions.v1AppsPermissionsCollectionGet({ "app_id": request["app_id"] as NonNullable<Parameters<YouVersionPlatformClient["permissions"]["v1AppsPermissionsCollectionGet"]>[0]>["app_id"] }, options).withRawResponse() },
  { ...metadata[14], execute: (client, request, options) => client.apps.v1AppsResourceGet({ "app_id": request["app_id"] as NonNullable<Parameters<YouVersionPlatformClient["apps"]["v1AppsResourceGet"]>[0]>["app_id"] }, options).withRawResponse() },
  { ...metadata[15], execute: (client, request, options) => client.fonts.v1FontsCollectionGet(options).withRawResponse() },
  { ...metadata[16], execute: (client, request, options) => client.fonts.v1FontsResourceGet({ "font_id": request["font_id"] as NonNullable<Parameters<YouVersionPlatformClient["fonts"]["v1FontsResourceGet"]>[0]>["font_id"] }, options).withRawResponse() },
  { ...metadata[17], execute: (client, request, options) => client.fonts.v1FontsStylesheetGet({ "font_id": request["font_id"] as NonNullable<Parameters<YouVersionPlatformClient["fonts"]["v1FontsStylesheetGet"]>[0]>["font_id"] }, options).withRawResponse() },
  { ...metadata[18], execute: (client, request, options) => client.highlights.v1HighlightsCollectionGet({ "bible_id": request["bible_id"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionGet"]>[0]>["bible_id"], "passage_id": request["passage_id"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionGet"]>[0]>["passage_id"] }, options).withRawResponse() },
  { ...metadata[19], execute: (client, request, options) => client.highlights.v1HighlightsCollectionPost({ "request_id": request["request_id"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionPost"]>[0]>["request_id"], "highlight": request["highlight"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionPost"]>[0]>["highlight"] }, options).withRawResponse() },
  { ...metadata[20], execute: (client, request, options) => client.highlights.v1HighlightsResourceDelete({ "passage_id_path": request["passage_id_path"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsResourceDelete"]>[0]>["passage_id_path"], "bible_id": request["bible_id"] as NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsResourceDelete"]>[0]>["bible_id"] }, options).withRawResponse() },
  { ...metadata[21], execute: (client, request, options) => client.languages.v1LanguagesCollectionGet({ "page_size": request["page_size"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>["page_size"], "fields[]": request["fields[]"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>["fields[]"], "page_token": request["page_token"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>["page_token"], "country": request["country"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>["country"], "bibles_available": request["bibles_available"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>["bibles_available"] }, options).withRawResponse() },
  { ...metadata[22], execute: (client, request, options) => client.languages.v1LanguagesResourceGet({ "language_id": request["language_id"] as NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesResourceGet"]>[0]>["language_id"] }, options).withRawResponse() },
  { ...metadata[23], execute: (client, request, options) => client.licenses.v1LicensesCollectionGet({ "bible_id": request["bible_id"] as NonNullable<Parameters<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>[0]>["bible_id"], "developer_id": request["developer_id"] as NonNullable<Parameters<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>[0]>["developer_id"], "all_available": request["all_available"] as NonNullable<Parameters<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>[0]>["all_available"] }, options).withRawResponse() },
  { ...metadata[24], execute: (client, request, options) => client.organizations.v1OrganizationsBiblesCollectionGet({ "organization_id": request["organization_id"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>[0]>["organization_id"], "page_size": request["page_size"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>[0]>["page_size"], "fields[]": request["fields[]"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>[0]>["fields[]"], "page_token": request["page_token"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>[0]>["page_token"] }, options).withRawResponse() },
  { ...metadata[25], execute: (client, request, options) => client.organizations.v1OrganizationsCollectionGet({ "bible_ids[]": request["bible_ids[]"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>[0]>["bible_ids[]"], "page_size": request["page_size"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>[0]>["page_size"], "fields[]": request["fields[]"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>[0]>["fields[]"], "page_token": request["page_token"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>[0]>["page_token"] }, options).withRawResponse() },
  { ...metadata[26], execute: (client, request, options) => client.organizations.v1OrganizationsResourceGet({ "organization_id": request["organization_id"] as NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsResourceGet"]>[0]>["organization_id"] }, options).withRawResponse() },
  { ...metadata[27], execute: (client, request, options) => client.searchQueries.v1SearchQueriesCollectionGet({ "language_ranges[]": request["language_ranges[]"] as NonNullable<Parameters<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>[0]>["language_ranges[]"], "query": request["query"] as NonNullable<Parameters<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>[0]>["query"], "trending": request["trending"] as NonNullable<Parameters<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>[0]>["trending"] }, options).withRawResponse() },
  { ...metadata[28], execute: (client, request, options) => client.searchTopics.v1SearchTopicsCollectionGet({ "query": request["query"] as NonNullable<Parameters<YouVersionPlatformClient["searchTopics"]["v1SearchTopicsCollectionGet"]>[0]>["query"], "language_ranges[]": request["language_ranges[]"] as NonNullable<Parameters<YouVersionPlatformClient["searchTopics"]["v1SearchTopicsCollectionGet"]>[0]>["language_ranges[]"] }, options).withRawResponse() },
  { ...metadata[29], execute: (client, request, options) => client.searchUnified.v1SearchUnifiedCollectionGet({ "query": request["query"] as NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>["query"], "bible_id": request["bible_id"] as NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>["bible_id"], "language_ranges[]": request["language_ranges[]"] as NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>["language_ranges[]"], "user_intent": request["user_intent"] as NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>["user_intent"], "fields[]": request["fields[]"] as NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>["fields[]"] }, options).withRawResponse() },
  { ...metadata[30], execute: (client, request, options) => client.searchVerses.v1SearchVersesCollectionGet({ "query": request["query"] as NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>["query"], "bible_id": request["bible_id"] as NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>["bible_id"], "user_intent": request["user_intent"] as NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>["user_intent"], "page_size": request["page_size"] as NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>["page_size"], "page_token": request["page_token"] as NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>["page_token"] }, options).withRawResponse() },
  { ...metadata[31], execute: (client, request, options) => client.verseOfTheDays.v1VerseOfTheDaysCanonicalCollectionGet(options).withRawResponse() },
  { ...metadata[32], execute: (client, request, options) => client.verseOfTheDays.v1VerseOfTheDaysCanonicalResourceGet({ "day": request["day"] as NonNullable<Parameters<YouVersionPlatformClient["verseOfTheDays"]["v1VerseOfTheDaysCanonicalResourceGet"]>[0]>["day"] }, options).withRawResponse() },
];
