# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawLanguagesClient, RawLanguagesClient
from .types.v1languages_collection_get_request_page_size import V1LanguagesCollectionGetRequestPageSize
from .types.v1languages_collection_get_response import V1LanguagesCollectionGetResponse
from .types.v1languages_resource_get_response import V1LanguagesResourceGetResponse


class LanguagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLanguagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLanguagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLanguagesClient
        """
        return self._raw_client

    def v1languages_collection_get(
        self,
        *,
        page_size: typing.Optional[V1LanguagesCollectionGetRequestPageSize] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        page_token: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        bibles_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[V1LanguagesCollectionGetResponse]:
        """
        Get a collection of language objects. Add the Country parameter to filter to prominent languages for that country. Send an Accept-Language header to control which name is returned in each language's localized_name; the negotiated locale is echoed in the Content-Language response header. Each object's display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names (and use page_size) when you only need localized_name.

        Parameters
        ----------
        page_size : typing.Optional[V1LanguagesCollectionGetRequestPageSize]
            The number of items to return in the collection.  Numeric values must be between 1 and 99.
            Special value "*" is supported only when used in combination with the `fields` parameter and
            when the client requests three or fewer fields (see `fields` parameter). When "*" is used the
            server will return all matching items for the requested resource (no numeric page limit).

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of top-level fields to include in each resource object. Use bracket notation to pass
            multiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.
            When provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        country : typing.Optional[str]
            The ISO 3166 2 character country code

        bibles_available : typing.Optional[bool]
            Filter languages based on whether Bible content is available for that language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[V1LanguagesCollectionGetResponse]
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.languages.v1languages_collection_get(
            page_token="eyJzdGFydF9hdCI6IDI2fQ==",
            country="US",
        )
        """
        _response = self._raw_client.v1languages_collection_get(
            page_size=page_size,
            fields=fields,
            page_token=page_token,
            country=country,
            bibles_available=bibles_available,
            request_options=request_options,
        )
        return _response.data

    def v1languages_resource_get(
        self, language_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V1LanguagesResourceGetResponse:
        """
        Get a single language resource by its BCP47 language code. Send an Accept-Language header to control which name is returned in localized_name; the negotiated locale is echoed in the Content-Language response header. The display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names when you only need localized_name.

        Parameters
        ----------
        language_id : str
            The language identifier uses the canonical BCP 47 language code, optionally including the script subtag when it distinguishes writing systems (for example, sr-Latn vs sr-Cyrl). Region subtags are excluded because they usually represent contextual or user-specific preferences rather than the intrinsic identity of the language, with one exception: a small, enumerated set of region variants that speakers treat as distinct languages is preserved (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Every other region, plus variants and extensions, is excluded, and a request for one redirects to the canonical region-agnostic id. This keeps identifiers stable and minimal while still surfacing the variants users distinguish.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1LanguagesResourceGetResponse
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.languages.v1languages_resource_get(
            language_id="en",
        )
        """
        _response = self._raw_client.v1languages_resource_get(language_id, request_options=request_options)
        return _response.data


class AsyncLanguagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLanguagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLanguagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLanguagesClient
        """
        return self._raw_client

    async def v1languages_collection_get(
        self,
        *,
        page_size: typing.Optional[V1LanguagesCollectionGetRequestPageSize] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        page_token: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        bibles_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[V1LanguagesCollectionGetResponse]:
        """
        Get a collection of language objects. Add the Country parameter to filter to prominent languages for that country. Send an Accept-Language header to control which name is returned in each language's localized_name; the negotiated locale is echoed in the Content-Language response header. Each object's display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names (and use page_size) when you only need localized_name.

        Parameters
        ----------
        page_size : typing.Optional[V1LanguagesCollectionGetRequestPageSize]
            The number of items to return in the collection.  Numeric values must be between 1 and 99.
            Special value "*" is supported only when used in combination with the `fields` parameter and
            when the client requests three or fewer fields (see `fields` parameter). When "*" is used the
            server will return all matching items for the requested resource (no numeric page limit).

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of top-level fields to include in each resource object. Use bracket notation to pass
            multiple values, for example: `fields[]=id&fields[]=name&fields[]=language`.
            When provided, `page_size=*` is allowed only if the number of fields requested is three (3) or fewer.

        page_token : typing.Optional[str]
            The page token to retrieve results from.

        country : typing.Optional[str]
            The ISO 3166 2 character country code

        bibles_available : typing.Optional[bool]
            Filter languages based on whether Bible content is available for that language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[V1LanguagesCollectionGetResponse]
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.languages.v1languages_collection_get(
                page_token="eyJzdGFydF9hdCI6IDI2fQ==",
                country="US",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1languages_collection_get(
            page_size=page_size,
            fields=fields,
            page_token=page_token,
            country=country,
            bibles_available=bibles_available,
            request_options=request_options,
        )
        return _response.data

    async def v1languages_resource_get(
        self, language_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V1LanguagesResourceGetResponse:
        """
        Get a single language resource by its BCP47 language code. Send an Accept-Language header to control which name is returned in localized_name; the negotiated locale is echoed in the Content-Language response header. The display_names map carries a name in every supported locale and is therefore large, so request fields[] without display_names when you only need localized_name.

        Parameters
        ----------
        language_id : str
            The language identifier uses the canonical BCP 47 language code, optionally including the script subtag when it distinguishes writing systems (for example, sr-Latn vs sr-Cyrl). Region subtags are excluded because they usually represent contextual or user-specific preferences rather than the intrinsic identity of the language, with one exception: a small, enumerated set of region variants that speakers treat as distinct languages is preserved (es-419, es-ES, pt-BR, pt-PT, zh-Hant-HK, zh-Hant-TW). Every other region, plus variants and extensions, is excluded, and a request for one redirects to the canonical region-agnostic id. This keeps identifiers stable and minimal while still surfacing the variants users distinguish.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1LanguagesResourceGetResponse
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.languages.v1languages_resource_get(
                language_id="en",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1languages_resource_get(language_id, request_options=request_options)
        return _response.data
