# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawLicensesClient, RawLicensesClient
from .types.v1licenses_collection_get_response import V1LicensesCollectionGetResponse


class LicensesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLicensesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLicensesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLicensesClient
        """
        return self._raw_client

    def v1licenses_collection_get(
        self,
        *,
        bible_id: int,
        developer_id: str,
        all_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1LicensesCollectionGetResponse:
        """
        Returns a list of license metadata. By default, the response returns all licenses.
        In the case that `developer_id` is passed in the query, it filters to only include licenses
        the developer has agreed to. In the case that `bible_id` is passed it only returns the
        license under which that Bible ID is currently licensed. The license object also contains
        a list of all Bible ids are offered under that license.
        Optionally combine `developer_id` with the `all_available` query parameter to receive
        every license while still surfacing the developer's agreement metadata when present.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        developer_id : str
            The Developer's unique ID in the Platform.

        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1LicensesCollectionGetResponse
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.licenses.v1licenses_collection_get(
            bible_id=1,
            developer_id="d0338b35-fe38-4ce4-b5fe-71e9a4a9a4c8",
        )
        """
        _response = self._raw_client.v1licenses_collection_get(
            bible_id=bible_id, developer_id=developer_id, all_available=all_available, request_options=request_options
        )
        return _response.data


class AsyncLicensesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLicensesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLicensesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLicensesClient
        """
        return self._raw_client

    async def v1licenses_collection_get(
        self,
        *,
        bible_id: int,
        developer_id: str,
        all_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V1LicensesCollectionGetResponse:
        """
        Returns a list of license metadata. By default, the response returns all licenses.
        In the case that `developer_id` is passed in the query, it filters to only include licenses
        the developer has agreed to. In the case that `bible_id` is passed it only returns the
        license under which that Bible ID is currently licensed. The license object also contains
        a list of all Bible ids are offered under that license.
        Optionally combine `developer_id` with the `all_available` query parameter to receive
        every license while still surfacing the developer's agreement metadata when present.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        developer_id : str
            The Developer's unique ID in the Platform.

        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1LicensesCollectionGetResponse
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.licenses.v1licenses_collection_get(
                bible_id=1,
                developer_id="d0338b35-fe38-4ce4-b5fe-71e9a4a9a4c8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1licenses_collection_get(
            bible_id=bible_id, developer_id=developer_id, all_available=all_available, request_options=request_options
        )
        return _response.data
