# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1licenses_collection_get_response import V1LicensesCollectionGetResponse
from pydantic import ValidationError


class RawLicensesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1licenses_collection_get(
        self,
        *,
        bible_id: int,
        developer_id: str,
        all_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[V1LicensesCollectionGetResponse]:
        """
        Returns a list of license metadata. By default, the response returns all licenses.
        In the case that `developer_id` is passed in the query, it filters to only include licenses
        the developer has agreed to. In the case that `bible_id` is passed it only returns the
        license under which that Bible ID is currently licensed. The license object also contains
        a list of all Bible ids are offered under that license.
        Optionally combine `developer_id` with the `all_available` query parameter to receive
        every license while still surfacing the developer's agreement metadata when present.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        developer_id : str
            The Developer's unique ID in the Platform.

        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1LicensesCollectionGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/licenses",
            method="GET",
            params={
                "bible_id": bible_id,
                "developer_id": developer_id,
                "all_available": all_available,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1LicensesCollectionGetResponse,
                    parse_obj_as(
                        type_=V1LicensesCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawLicensesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1licenses_collection_get(
        self,
        *,
        bible_id: int,
        developer_id: str,
        all_available: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[V1LicensesCollectionGetResponse]:
        """
        Returns a list of license metadata. By default, the response returns all licenses.
        In the case that `developer_id` is passed in the query, it filters to only include licenses
        the developer has agreed to. In the case that `bible_id` is passed it only returns the
        license under which that Bible ID is currently licensed. The license object also contains
        a list of all Bible ids are offered under that license.
        Optionally combine `developer_id` with the `all_available` query parameter to receive
        every license while still surfacing the developer's agreement metadata when present.

        Parameters
        ----------
        bible_id : int
            The Bible version identifier

        developer_id : str
            The Developer's unique ID in the Platform.

        all_available : typing.Optional[bool]
            This parameter is used on some collections to modify the resources returned. For example, it modifies whether all Bibles in the Platform should be included in the Bibles collection regardless of licensing of the provided app key. It modified the Licenses collection so that the response will include every license, regardless of whether the developer has agreed to it yet. The default for this field in all cases is false. If a developer wants to include all resources for a collection that implements this query parameter, the client must specifically pass it as true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1LicensesCollectionGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/licenses",
            method="GET",
            params={
                "bible_id": bible_id,
                "developer_id": developer_id,
                "all_available": all_available,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1LicensesCollectionGetResponse,
                    parse_obj_as(
                        type_=V1LicensesCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
