// Code generated by Fern. DO NOT EDIT.

package core

import (
	http "net/http"
	url "net/url"
)

// RequestOption adapts the behavior of the client or an individual request.
type RequestOption interface {
	applyRequestOptions(*RequestOptions)
}

// RequestOptions defines all of the possible request options.
//
// This type is primarily used by the generated code and is not meant
// to be used directly; use the option package instead.
type RequestOptions struct {
	BaseURL                    string
	HTTPClient                 HTTPClient
	HTTPHeader                 http.Header
	BodyProperties             map[string]interface{}
	QueryParameters            url.Values
	MaxAttempts                uint
	MaxBufSize                 int
	MaxStreamReconnectAttempts uint
	DisableStreamReconnection  bool
	DisableRetries             bool
	Token                      string
	TokenFunc                  func() (string, error)
	YvpAppKey                  string
}

// NewRequestOptions returns a new *RequestOptions value.
//
// This function is primarily used by the generated code and is not meant
// to be used directly; use RequestOption instead.
func NewRequestOptions(opts ...RequestOption) *RequestOptions {
	options := &RequestOptions{
		HTTPHeader:      make(http.Header),
		BodyProperties:  make(map[string]interface{}),
		QueryParameters: make(url.Values),
	}
	for _, opt := range opts {
		opt.applyRequestOptions(options)
	}
	return options
}

// ToHeader maps the configured request options into a http.Header used
// for the request(s).
func (r *RequestOptions) ToHeader(overrides *RequestOptions, includeAuth bool) (http.Header, error) {
	header := make(http.Header)
	for _, values := range []http.Header{r.HTTPHeader, overrides.HTTPHeader} {
		for name, value := range values {
			header[http.CanonicalHeaderKey(name)] = append([]string(nil), value...)
		}
	}
	appKey := r.YvpAppKey
	if overrides.YvpAppKey != "" {
		appKey = overrides.YvpAppKey
	}
	header.Set("X-YVP-App-Key", appKey)
	if !includeAuth {
		header.Del("Authorization")
		return header, nil
	}
	token, tokenFunc := r.Token, r.TokenFunc
	if overrides.Token != "" || overrides.TokenFunc != nil {
		token, tokenFunc = overrides.Token, overrides.TokenFunc
	}
	if token == "" && tokenFunc != nil {
		var err error
		token, err = tokenFunc()
		if err != nil {
			return nil, err
		}
	}
	if token != "" {
		header.Set("Authorization", "Bearer "+token)
	}
	return header, nil
}

// BaseURLOption implements the RequestOption interface.
type BaseURLOption struct {
	BaseURL string
}

func (b *BaseURLOption) applyRequestOptions(opts *RequestOptions) {
	opts.BaseURL = b.BaseURL
}

// HTTPClientOption implements the RequestOption interface.
type HTTPClientOption struct {
	HTTPClient HTTPClient
}

func (h *HTTPClientOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPClient = h.HTTPClient
}

// HTTPHeaderOption implements the RequestOption interface.
type HTTPHeaderOption struct {
	HTTPHeader http.Header
}

func (h *HTTPHeaderOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPHeader = h.HTTPHeader
}

// BodyPropertiesOption implements the RequestOption interface.
type BodyPropertiesOption struct {
	BodyProperties map[string]interface{}
}

func (b *BodyPropertiesOption) applyRequestOptions(opts *RequestOptions) {
	opts.BodyProperties = b.BodyProperties
}

// QueryParametersOption implements the RequestOption interface.
type QueryParametersOption struct {
	QueryParameters url.Values
}

func (q *QueryParametersOption) applyRequestOptions(opts *RequestOptions) {
	opts.QueryParameters = q.QueryParameters
}

// MaxAttemptsOption implements the RequestOption interface.
type MaxAttemptsOption struct {
	MaxAttempts uint
}

func (m *MaxAttemptsOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxAttempts = m.MaxAttempts
}

// MaxBufSizeOption implements the RequestOption interface.
type MaxBufSizeOption struct {
	MaxBufSize int
}

func (m *MaxBufSizeOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxBufSize = m.MaxBufSize
}

// MaxStreamReconnectAttemptsOption implements the RequestOption interface.
type MaxStreamReconnectAttemptsOption struct {
	MaxStreamReconnectAttempts uint
}

func (m *MaxStreamReconnectAttemptsOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxStreamReconnectAttempts = m.MaxStreamReconnectAttempts
}

// WithoutStreamReconnectionOption implements the RequestOption interface.
type WithoutStreamReconnectionOption struct{}

func (w *WithoutStreamReconnectionOption) applyRequestOptions(opts *RequestOptions) {
	opts.DisableStreamReconnection = true
}

// WithoutRetriesOption implements the RequestOption interface.
type WithoutRetriesOption struct{}

func (w *WithoutRetriesOption) applyRequestOptions(opts *RequestOptions) {
	opts.DisableRetries = true
}

// TokenOption implements the RequestOption interface.
type TokenOption struct {
	Token string
}

func (t *TokenOption) applyRequestOptions(opts *RequestOptions) {
	opts.Token = t.Token
}

// TokenFuncOption implements the RequestOption interface.
type TokenFuncOption struct {
	TokenFunc func() (string, error)
}

func (t *TokenFuncOption) applyRequestOptions(opts *RequestOptions) {
	opts.TokenFunc = t.TokenFunc
}

// YvpAppKeyOption implements the RequestOption interface.
type YvpAppKeyOption struct {
	YvpAppKey string
}

func (y *YvpAppKeyOption) applyRequestOptions(opts *RequestOptions) {
	opts.YvpAppKey = y.YvpAppKey
}
