// Code generated by Fern. DO NOT EDIT.

package client

import (
	apps "github.com/cameronapak/Platform-SDK-TS/packages/go/apps"
	bibles "github.com/cameronapak/Platform-SDK-TS/packages/go/bibles"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	dataexchange "github.com/cameronapak/Platform-SDK-TS/packages/go/dataexchange"
	fonts "github.com/cameronapak/Platform-SDK-TS/packages/go/fonts"
	highlights "github.com/cameronapak/Platform-SDK-TS/packages/go/highlights"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	languages "github.com/cameronapak/Platform-SDK-TS/packages/go/languages"
	licenses "github.com/cameronapak/Platform-SDK-TS/packages/go/licenses"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
	organizations "github.com/cameronapak/Platform-SDK-TS/packages/go/organizations"
	permissions "github.com/cameronapak/Platform-SDK-TS/packages/go/permissions"
	searchqueries "github.com/cameronapak/Platform-SDK-TS/packages/go/searchqueries"
	searchtopics "github.com/cameronapak/Platform-SDK-TS/packages/go/searchtopics"
	searchunified "github.com/cameronapak/Platform-SDK-TS/packages/go/searchunified"
	searchverses "github.com/cameronapak/Platform-SDK-TS/packages/go/searchverses"
	verseofthedays "github.com/cameronapak/Platform-SDK-TS/packages/go/verseofthedays"
)

type PlatformClient struct {
	DataExchange   *dataexchange.Client
	Bibles         *bibles.Client
	Highlights     *highlights.Client
	Fonts          *fonts.Client
	SearchQueries  *searchqueries.Client
	SearchUnified  *searchunified.Client
	SearchTopics   *searchtopics.Client
	SearchVerses   *searchverses.Client
	Languages      *languages.Client
	Licenses       *licenses.Client
	Apps           *apps.Client
	Permissions    *permissions.Client
	Organizations  *organizations.Client
	VerseOfTheDays *verseofthedays.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewPlatformClient(opts ...option.RequestOption) *PlatformClient {
	options := core.NewRequestOptions(opts...)
	return &PlatformClient{
		DataExchange:   dataexchange.NewClient(options),
		Bibles:         bibles.NewClient(options),
		Highlights:     highlights.NewClient(options),
		Fonts:          fonts.NewClient(options),
		SearchQueries:  searchqueries.NewClient(options),
		SearchUnified:  searchunified.NewClient(options),
		SearchTopics:   searchtopics.NewClient(options),
		SearchVerses:   searchverses.NewClient(options),
		Languages:      languages.NewClient(options),
		Licenses:       licenses.NewClient(options),
		Apps:           apps.NewClient(options),
		Permissions:    permissions.NewClient(options),
		Organizations:  organizations.NewClient(options),
		VerseOfTheDays: verseofthedays.NewClient(options),
		options:        options,
		baseURL:        options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
