# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1fonts_collection_get_response import V1FontsCollectionGetResponse
from .types.v1fonts_resource_get_response import V1FontsResourceGetResponse
from pydantic import ValidationError


class RawFontsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1fonts_collection_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[V1FontsCollectionGetResponse]:
        """
        Get a collection of font family resources with their available variants and CDN sources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1FontsCollectionGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/fonts",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1FontsCollectionGetResponse,
                    parse_obj_as(
                        type_=V1FontsCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def v1fonts_resource_get(
        self, font_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[V1FontsResourceGetResponse]:
        """
        Get a single font family resource by its integer identifier.

        Parameters
        ----------
        font_id : int
            The unique integer identifier for a font family resource in the Platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1FontsResourceGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/fonts/{encode_path_param(font_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1FontsResourceGetResponse,
                    parse_obj_as(
                        type_=V1FontsResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def v1fonts_stylesheet_get(
        self, font_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[str]:
        """
        Get a text/css stylesheet for a single font family resource using the canonical woff2 CDN URLs exposed by the JSON Fonts API for browser consumption. The API gateway accepts `app_key` on this route and injects the required app-id header before forwarding the request to this service.

        Parameters
        ----------
        font_id : int
            The unique integer identifier for a font family resource in the Platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[str]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/fonts/{encode_path_param(font_id)}/stylesheet",
            method="GET",
            params={"app_key": self._client_wrapper.get_app_key()},
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=_response.text)  # type: ignore
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFontsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1fonts_collection_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[V1FontsCollectionGetResponse]:
        """
        Get a collection of font family resources with their available variants and CDN sources.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1FontsCollectionGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/fonts",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1FontsCollectionGetResponse,
                    parse_obj_as(
                        type_=V1FontsCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def v1fonts_resource_get(
        self, font_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[V1FontsResourceGetResponse]:
        """
        Get a single font family resource by its integer identifier.

        Parameters
        ----------
        font_id : int
            The unique integer identifier for a font family resource in the Platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1FontsResourceGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/fonts/{encode_path_param(font_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1FontsResourceGetResponse,
                    parse_obj_as(
                        type_=V1FontsResourceGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def v1fonts_stylesheet_get(
        self, font_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[str]:
        """
        Get a text/css stylesheet for a single font family resource using the canonical woff2 CDN URLs exposed by the JSON Fonts API for browser consumption. The API gateway accepts `app_key` on this route and injects the required app-id header before forwarding the request to this service.

        Parameters
        ----------
        font_id : int
            The unique integer identifier for a font family resource in the Platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[str]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/fonts/{encode_path_param(font_id)}/stylesheet",
            method="GET",
            params={"app_key": self._client_wrapper.get_app_key()},
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=_response.text)  # type: ignore
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
