// This file is generated by scripts/generate-react-query.mjs.

import type { YouVersionPlatformClient } from '@cameronapak/platform-sdk';
import type { MutationFilters, QueryFilters } from '@tanstack/react-query';
import {
  createMutationBinding,
  createOptionalQueryBinding,
  createRequestlessQueryBinding,
  createRequiredQueryBinding,
  resourceMutationFilters,
  resourceQueryFilters,
  rootMutationFilters,
  rootQueryFilters,
  validateCacheScope,
  type MutationBinding,
  type OptionalQueryBinding,
  type RequestlessQueryBinding,
  type RequiredQueryBinding,
} from './runtime.js';

type ClientMethod = (...args: never[]) => unknown;
type MethodRequest<TMethod extends ClientMethod> = NonNullable<Parameters<TMethod>[0]>;
type MethodResult<TMethod extends ClientMethod> = Awaited<ReturnType<TMethod>>;
type EmptyQueryResult<TResult> = Exclude<TResult, undefined> | null;

export interface CreatePlatformQueriesOptions {
  client: YouVersionPlatformClient;
  /** Non-secret identity and representation boundary for every cache entry. */
  cacheScope: string;
}

export interface PlatformQueries {
  queryFilters(): QueryFilters;
  mutationFilters(): MutationFilters;
  apps: {
    queryFilters(): QueryFilters;
    resourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["apps"]["v1AppsResourceGet"]>, MethodResult<YouVersionPlatformClient["apps"]["v1AppsResourceGet"]>>;
  };
  bibles: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["collectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["bibles"]["collectionGet"]>>>;
    resourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["resourceGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["resourceGet"]>>;
    booksCollectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["bibles"]["booksCollectionGet"]>>>;
    booksResourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksResourceGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["booksResourceGet"]>>;
    booksChaptersCollectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksChaptersCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["bibles"]["booksChaptersCollectionGet"]>>>;
    booksChaptersResourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>>;
    booksChaptersVersesCollectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>>>;
    booksChaptersVersesResourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>>;
    indexCollectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["indexCollectionGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["indexCollectionGet"]>>;
    passagesResourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>, MethodResult<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>>;
  };
  dataExchange: {
    mutationFilters(): MutationFilters;
    tokenPost: MutationBinding<MethodRequest<YouVersionPlatformClient["dataExchange"]["tokenPost"]>, MethodResult<YouVersionPlatformClient["dataExchange"]["tokenPost"]>>;
  };
  fonts: {
    queryFilters(): QueryFilters;
    collectionGet: RequestlessQueryBinding<MethodResult<YouVersionPlatformClient["fonts"]["v1FontsCollectionGet"]>>;
    resourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["fonts"]["v1FontsResourceGet"]>, MethodResult<YouVersionPlatformClient["fonts"]["v1FontsResourceGet"]>>;
    stylesheetGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["fonts"]["v1FontsStylesheetGet"]>, MethodResult<YouVersionPlatformClient["fonts"]["v1FontsStylesheetGet"]>>;
  };
  highlights: {
    queryFilters(): QueryFilters;
    mutationFilters(): MutationFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionGet"]>>>;
    collectionPost: MutationBinding<MethodRequest<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionPost"]>, MethodResult<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionPost"]>>;
    resourceDelete: MutationBinding<MethodRequest<YouVersionPlatformClient["highlights"]["v1HighlightsResourceDelete"]>, MethodResult<YouVersionPlatformClient["highlights"]["v1HighlightsResourceDelete"]>>;
  };
  languages: {
    queryFilters(): QueryFilters;
    collectionGet: OptionalQueryBinding<MethodRequest<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>>>;
    resourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["languages"]["v1LanguagesResourceGet"]>, MethodResult<YouVersionPlatformClient["languages"]["v1LanguagesResourceGet"]>>;
  };
  licenses: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>, MethodResult<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>>;
  };
  organizations: {
    queryFilters(): QueryFilters;
    biblesCollectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>, MethodResult<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>>;
    collectionGet: OptionalQueryBinding<MethodRequest<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>>>;
    resourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["organizations"]["v1OrganizationsResourceGet"]>, MethodResult<YouVersionPlatformClient["organizations"]["v1OrganizationsResourceGet"]>>;
  };
  permissions: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["permissions"]["v1AppsPermissionsCollectionGet"]>, MethodResult<YouVersionPlatformClient["permissions"]["v1AppsPermissionsCollectionGet"]>>;
  };
  searchQueries: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>, EmptyQueryResult<MethodResult<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>>>;
  };
  searchTopics: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["searchTopics"]["v1SearchTopicsCollectionGet"]>, MethodResult<YouVersionPlatformClient["searchTopics"]["v1SearchTopicsCollectionGet"]>>;
  };
  searchUnified: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>, MethodResult<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>>;
  };
  searchVerses: {
    queryFilters(): QueryFilters;
    collectionGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>, MethodResult<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>>;
  };
  verseOfTheDays: {
    queryFilters(): QueryFilters;
    canonicalCollectionGet: RequestlessQueryBinding<EmptyQueryResult<MethodResult<YouVersionPlatformClient["verseOfTheDays"]["v1VerseOfTheDaysCanonicalCollectionGet"]>>>;
    canonicalResourceGet: RequiredQueryBinding<MethodRequest<YouVersionPlatformClient["verseOfTheDays"]["v1VerseOfTheDaysCanonicalResourceGet"]>, MethodResult<YouVersionPlatformClient["verseOfTheDays"]["v1VerseOfTheDaysCanonicalResourceGet"]>>;
  };
}

export const reactQueryOperationManifest = {
  "bibles.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles","accessor":"bibles","method":"collectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":false},
  "bibles.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}","accessor":"bibles","method":"resourceGet","publicName":"resourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "bibles_books.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books","accessor":"bibles","method":"booksCollectionGet","publicName":"booksCollectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":false},
  "bibles_books.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books/{book_id}","accessor":"bibles","method":"booksResourceGet","publicName":"booksResourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "bibles_books_chapters.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books/{book_id}/chapters","accessor":"bibles","method":"booksChaptersCollectionGet","publicName":"booksChaptersCollectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":false},
  "bibles_books_chapters.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}","accessor":"bibles","method":"booksChaptersResourceGet","publicName":"booksChaptersResourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "bibles_books_chapters_verses.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}/verses","accessor":"bibles","method":"booksChaptersVersesCollectionGet","publicName":"booksChaptersVersesCollectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":false},
  "bibles_books_chapters_verses.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/books/{book_id}/chapters/{chapter_id}/verses/{verse_id}","accessor":"bibles","method":"booksChaptersVersesResourceGet","publicName":"booksChaptersVersesResourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "bibles_index.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/index","accessor":"bibles","method":"indexCollectionGet","publicName":"indexCollectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "bibles_passages.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/bibles/{bible_id_path}/passages/{passage_id_path}","accessor":"bibles","method":"passagesResourceGet","publicName":"passagesResourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "data_exchange.approval_get": {"kind":"excluded","httpMethod":"GET","path":"/data-exchange","accessor":"dataExchange","method":"approvalGet","publicName":"approvalGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false,"exclusionReason":"Browser approval action with a manual redirect"},
  "data_exchange.approval_post": {"kind":"excluded","httpMethod":"POST","path":"/data-exchange","accessor":"dataExchange","method":"approvalPost","publicName":"approvalPost","requestMode":"optional","emptySuccess":false,"requiresOAuth":false,"exclusionReason":"Browser approval action with a manual redirect"},
  "data_exchange.token_post": {"kind":"mutation","httpMethod":"POST","path":"/data-exchange/token","accessor":"dataExchange","method":"tokenPost","publicName":"tokenPost","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.apps.permissions.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/apps/{app_id}/permissions","accessor":"permissions","method":"v1AppsPermissionsCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":true},
  "v1.apps.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/apps/{app_id}","accessor":"apps","method":"v1AppsResourceGet","publicName":"resourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.fonts.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/fonts","accessor":"fonts","method":"v1FontsCollectionGet","publicName":"collectionGet","requestMode":"none","emptySuccess":false,"requiresOAuth":false},
  "v1.fonts.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/fonts/{font_id}","accessor":"fonts","method":"v1FontsResourceGet","publicName":"resourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.fonts.stylesheet_get": {"kind":"query","httpMethod":"GET","path":"/v1/fonts/{font_id}/stylesheet","accessor":"fonts","method":"v1FontsStylesheetGet","publicName":"stylesheetGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.highlights.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/highlights","accessor":"highlights","method":"v1HighlightsCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":true},
  "v1.highlights.collection_post": {"kind":"mutation","httpMethod":"POST","path":"/v1/highlights","accessor":"highlights","method":"v1HighlightsCollectionPost","publicName":"collectionPost","requestMode":"required","emptySuccess":false,"requiresOAuth":true},
  "v1.highlights.resource_delete": {"kind":"mutation","httpMethod":"DELETE","path":"/v1/highlights/{passage_id_path}","accessor":"highlights","method":"v1HighlightsResourceDelete","publicName":"resourceDelete","requestMode":"required","emptySuccess":true,"requiresOAuth":true},
  "v1.languages.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/languages","accessor":"languages","method":"v1LanguagesCollectionGet","publicName":"collectionGet","requestMode":"optional","emptySuccess":true,"requiresOAuth":false},
  "v1.languages.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/languages/{language_id}","accessor":"languages","method":"v1LanguagesResourceGet","publicName":"resourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.licenses.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/licenses","accessor":"licenses","method":"v1LicensesCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.organizations.bibles.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/organizations/{organization_id}/bibles","accessor":"organizations","method":"v1OrganizationsBiblesCollectionGet","publicName":"biblesCollectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.organizations.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/organizations","accessor":"organizations","method":"v1OrganizationsCollectionGet","publicName":"collectionGet","requestMode":"optional","emptySuccess":true,"requiresOAuth":false},
  "v1.organizations.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/organizations/{organization_id}","accessor":"organizations","method":"v1OrganizationsResourceGet","publicName":"resourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.search_queries.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/search-queries","accessor":"searchQueries","method":"v1SearchQueriesCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":true,"requiresOAuth":false},
  "v1.search_topics.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/search-topics","accessor":"searchTopics","method":"v1SearchTopicsCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.search_unified.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/search-unified","accessor":"searchUnified","method":"v1SearchUnifiedCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.search_verses.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/search-verses","accessor":"searchVerses","method":"v1SearchVersesCollectionGet","publicName":"collectionGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
  "v1.verse_of_the_days.canonical.collection_get": {"kind":"query","httpMethod":"GET","path":"/v1/verse-of-the-days","accessor":"verseOfTheDays","method":"v1VerseOfTheDaysCanonicalCollectionGet","publicName":"canonicalCollectionGet","requestMode":"none","emptySuccess":true,"requiresOAuth":false},
  "v1.verse_of_the_days.canonical.resource_get": {"kind":"query","httpMethod":"GET","path":"/v1/verse-of-the-days/{day}","accessor":"verseOfTheDays","method":"v1VerseOfTheDaysCanonicalResourceGet","publicName":"canonicalResourceGet","requestMode":"required","emptySuccess":false,"requiresOAuth":false},
} as const;

export function createPlatformQueries(options: CreatePlatformQueriesOptions): PlatformQueries {
  const client = options.client;
  const cacheScope = validateCacheScope(options.cacheScope);

  const biblesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles.collection_get",
    emptyAsNull: true,
    requestProperties: ["all_available","language_ranges[]","license_id","page_size","fields[]","page_token"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["collectionGet"]>[0]>,
      requestOptions,
    ) => client.bibles.collectionGet(request, requestOptions),
  });

  const biblesResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles.resource_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["resourceGet"]>[0]>,
      requestOptions,
    ) => client.bibles.resourceGet(request, requestOptions),
  });

  const biblesBooksCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books.collection_get",
    emptyAsNull: true,
    requestProperties: ["bible_id_path","canon"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksCollectionGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksCollectionGet(request, requestOptions),
  });

  const biblesBooksResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books.resource_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path","book_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksResourceGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksResourceGet(request, requestOptions),
  });

  const biblesBooksChaptersCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books_chapters.collection_get",
    emptyAsNull: true,
    requestProperties: ["bible_id_path","book_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersCollectionGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksChaptersCollectionGet(request, requestOptions),
  });

  const biblesBooksChaptersResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books_chapters.resource_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path","book_id","chapter_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersResourceGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksChaptersResourceGet(request, requestOptions),
  });

  const biblesBooksChaptersVersesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books_chapters_verses.collection_get",
    emptyAsNull: true,
    requestProperties: ["bible_id_path","book_id","chapter_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksChaptersVersesCollectionGet(request, requestOptions),
  });

  const biblesBooksChaptersVersesResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_books_chapters_verses.resource_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path","book_id","chapter_id","verse_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["booksChaptersVersesResourceGet"]>[0]>,
      requestOptions,
    ) => client.bibles.booksChaptersVersesResourceGet(request, requestOptions),
  });

  const biblesIndexCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_index.collection_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["indexCollectionGet"]>[0]>,
      requestOptions,
    ) => client.bibles.indexCollectionGet(request, requestOptions),
  });

  const biblesPassagesResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "bibles",
    operationId: "bibles_passages.resource_get",
    emptyAsNull: false,
    requestProperties: ["bible_id_path","passage_id_path","format","include_headings","include_notes"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["bibles"]["passagesResourceGet"]>[0]>,
      requestOptions,
    ) => client.bibles.passagesResourceGet(request, requestOptions),
  });

  const dataExchangeTokenPost = createMutationBinding({
    cacheScope,
    resource: "dataExchange",
    operationId: "data_exchange.token_post",
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["dataExchange"]["tokenPost"]>[0]>,
      requestOptions,
    ) => client.dataExchange.tokenPost(request, requestOptions),
  });

  const permissionsCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "permissions",
    operationId: "v1.apps.permissions.collection_get",
    emptyAsNull: false,
    requestProperties: ["app_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["permissions"]["v1AppsPermissionsCollectionGet"]>[0]>,
      requestOptions,
    ) => client.permissions.v1AppsPermissionsCollectionGet(request, requestOptions),
  });

  const appsResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "apps",
    operationId: "v1.apps.resource_get",
    emptyAsNull: false,
    requestProperties: ["app_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["apps"]["v1AppsResourceGet"]>[0]>,
      requestOptions,
    ) => client.apps.v1AppsResourceGet(request, requestOptions),
  });

  const fontsCollectionGet = createRequestlessQueryBinding({
    cacheScope,
    resource: "fonts",
    operationId: "v1.fonts.collection_get",
    emptyAsNull: false,
    execute: (requestOptions) => client.fonts.v1FontsCollectionGet(requestOptions),
  });

  const fontsResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "fonts",
    operationId: "v1.fonts.resource_get",
    emptyAsNull: false,
    requestProperties: ["font_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["fonts"]["v1FontsResourceGet"]>[0]>,
      requestOptions,
    ) => client.fonts.v1FontsResourceGet(request, requestOptions),
  });

  const fontsStylesheetGet = createRequiredQueryBinding({
    cacheScope,
    resource: "fonts",
    operationId: "v1.fonts.stylesheet_get",
    emptyAsNull: false,
    requestProperties: ["font_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["fonts"]["v1FontsStylesheetGet"]>[0]>,
      requestOptions,
    ) => client.fonts.v1FontsStylesheetGet(request, requestOptions),
  });

  const highlightsCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "highlights",
    operationId: "v1.highlights.collection_get",
    emptyAsNull: true,
    requestProperties: ["bible_id","passage_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionGet"]>[0]>,
      requestOptions,
    ) => client.highlights.v1HighlightsCollectionGet(request, requestOptions),
  });

  const highlightsCollectionPost = createMutationBinding({
    cacheScope,
    resource: "highlights",
    operationId: "v1.highlights.collection_post",
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsCollectionPost"]>[0]>,
      requestOptions,
    ) => client.highlights.v1HighlightsCollectionPost(request, requestOptions),
  });

  const highlightsResourceDelete = createMutationBinding({
    cacheScope,
    resource: "highlights",
    operationId: "v1.highlights.resource_delete",
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["highlights"]["v1HighlightsResourceDelete"]>[0]>,
      requestOptions,
    ) => client.highlights.v1HighlightsResourceDelete(request, requestOptions),
  });

  const languagesCollectionGet = createOptionalQueryBinding({
    cacheScope,
    resource: "languages",
    operationId: "v1.languages.collection_get",
    emptyAsNull: true,
    requestProperties: ["page_size","fields[]","page_token","country","bibles_available"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.languages.v1LanguagesCollectionGet(request, requestOptions),
  });

  const languagesResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "languages",
    operationId: "v1.languages.resource_get",
    emptyAsNull: false,
    requestProperties: ["language_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["languages"]["v1LanguagesResourceGet"]>[0]>,
      requestOptions,
    ) => client.languages.v1LanguagesResourceGet(request, requestOptions),
  });

  const licensesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "licenses",
    operationId: "v1.licenses.collection_get",
    emptyAsNull: false,
    requestProperties: ["bible_id","developer_id","all_available"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["licenses"]["v1LicensesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.licenses.v1LicensesCollectionGet(request, requestOptions),
  });

  const organizationsBiblesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "organizations",
    operationId: "v1.organizations.bibles.collection_get",
    emptyAsNull: false,
    requestProperties: ["organization_id","page_size","fields[]","page_token"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsBiblesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.organizations.v1OrganizationsBiblesCollectionGet(request, requestOptions),
  });

  const organizationsCollectionGet = createOptionalQueryBinding({
    cacheScope,
    resource: "organizations",
    operationId: "v1.organizations.collection_get",
    emptyAsNull: true,
    requestProperties: ["bible_ids[]","page_size","fields[]","page_token"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsCollectionGet"]>[0]>,
      requestOptions,
    ) => client.organizations.v1OrganizationsCollectionGet(request, requestOptions),
  });

  const organizationsResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "organizations",
    operationId: "v1.organizations.resource_get",
    emptyAsNull: false,
    requestProperties: ["organization_id"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["organizations"]["v1OrganizationsResourceGet"]>[0]>,
      requestOptions,
    ) => client.organizations.v1OrganizationsResourceGet(request, requestOptions),
  });

  const searchQueriesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "searchQueries",
    operationId: "v1.search_queries.collection_get",
    emptyAsNull: true,
    requestProperties: ["language_ranges[]","query","trending"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["searchQueries"]["v1SearchQueriesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.searchQueries.v1SearchQueriesCollectionGet(request, requestOptions),
  });

  const searchTopicsCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "searchTopics",
    operationId: "v1.search_topics.collection_get",
    emptyAsNull: false,
    requestProperties: ["query","language_ranges[]"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["searchTopics"]["v1SearchTopicsCollectionGet"]>[0]>,
      requestOptions,
    ) => client.searchTopics.v1SearchTopicsCollectionGet(request, requestOptions),
  });

  const searchUnifiedCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "searchUnified",
    operationId: "v1.search_unified.collection_get",
    emptyAsNull: false,
    requestProperties: ["query","bible_id","language_ranges[]","user_intent","fields[]"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["searchUnified"]["v1SearchUnifiedCollectionGet"]>[0]>,
      requestOptions,
    ) => client.searchUnified.v1SearchUnifiedCollectionGet(request, requestOptions),
  });

  const searchVersesCollectionGet = createRequiredQueryBinding({
    cacheScope,
    resource: "searchVerses",
    operationId: "v1.search_verses.collection_get",
    emptyAsNull: false,
    requestProperties: ["query","bible_id","user_intent","page_size","page_token"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["searchVerses"]["v1SearchVersesCollectionGet"]>[0]>,
      requestOptions,
    ) => client.searchVerses.v1SearchVersesCollectionGet(request, requestOptions),
  });

  const verseOfTheDaysCanonicalCollectionGet = createRequestlessQueryBinding({
    cacheScope,
    resource: "verseOfTheDays",
    operationId: "v1.verse_of_the_days.canonical.collection_get",
    emptyAsNull: true,
    execute: (requestOptions) => client.verseOfTheDays.v1VerseOfTheDaysCanonicalCollectionGet(requestOptions),
  });

  const verseOfTheDaysCanonicalResourceGet = createRequiredQueryBinding({
    cacheScope,
    resource: "verseOfTheDays",
    operationId: "v1.verse_of_the_days.canonical.resource_get",
    emptyAsNull: false,
    requestProperties: ["day"],
    execute: (
      request: NonNullable<Parameters<YouVersionPlatformClient["verseOfTheDays"]["v1VerseOfTheDaysCanonicalResourceGet"]>[0]>,
      requestOptions,
    ) => client.verseOfTheDays.v1VerseOfTheDaysCanonicalResourceGet(request, requestOptions),
  });

  return {
    queryFilters: () => rootQueryFilters(cacheScope),
    mutationFilters: () => rootMutationFilters(cacheScope),
    apps: {
      queryFilters: () => resourceQueryFilters(cacheScope, "apps"),
      resourceGet: appsResourceGet,
    },
    bibles: {
      queryFilters: () => resourceQueryFilters(cacheScope, "bibles"),
      collectionGet: biblesCollectionGet,
      resourceGet: biblesResourceGet,
      booksCollectionGet: biblesBooksCollectionGet,
      booksResourceGet: biblesBooksResourceGet,
      booksChaptersCollectionGet: biblesBooksChaptersCollectionGet,
      booksChaptersResourceGet: biblesBooksChaptersResourceGet,
      booksChaptersVersesCollectionGet: biblesBooksChaptersVersesCollectionGet,
      booksChaptersVersesResourceGet: biblesBooksChaptersVersesResourceGet,
      indexCollectionGet: biblesIndexCollectionGet,
      passagesResourceGet: biblesPassagesResourceGet,
    },
    dataExchange: {
      mutationFilters: () => resourceMutationFilters(cacheScope, "dataExchange"),
      tokenPost: dataExchangeTokenPost,
    },
    fonts: {
      queryFilters: () => resourceQueryFilters(cacheScope, "fonts"),
      collectionGet: fontsCollectionGet,
      resourceGet: fontsResourceGet,
      stylesheetGet: fontsStylesheetGet,
    },
    highlights: {
      queryFilters: () => resourceQueryFilters(cacheScope, "highlights"),
      mutationFilters: () => resourceMutationFilters(cacheScope, "highlights"),
      collectionGet: highlightsCollectionGet,
      collectionPost: highlightsCollectionPost,
      resourceDelete: highlightsResourceDelete,
    },
    languages: {
      queryFilters: () => resourceQueryFilters(cacheScope, "languages"),
      collectionGet: languagesCollectionGet,
      resourceGet: languagesResourceGet,
    },
    licenses: {
      queryFilters: () => resourceQueryFilters(cacheScope, "licenses"),
      collectionGet: licensesCollectionGet,
    },
    organizations: {
      queryFilters: () => resourceQueryFilters(cacheScope, "organizations"),
      biblesCollectionGet: organizationsBiblesCollectionGet,
      collectionGet: organizationsCollectionGet,
      resourceGet: organizationsResourceGet,
    },
    permissions: {
      queryFilters: () => resourceQueryFilters(cacheScope, "permissions"),
      collectionGet: permissionsCollectionGet,
    },
    searchQueries: {
      queryFilters: () => resourceQueryFilters(cacheScope, "searchQueries"),
      collectionGet: searchQueriesCollectionGet,
    },
    searchTopics: {
      queryFilters: () => resourceQueryFilters(cacheScope, "searchTopics"),
      collectionGet: searchTopicsCollectionGet,
    },
    searchUnified: {
      queryFilters: () => resourceQueryFilters(cacheScope, "searchUnified"),
      collectionGet: searchUnifiedCollectionGet,
    },
    searchVerses: {
      queryFilters: () => resourceQueryFilters(cacheScope, "searchVerses"),
      collectionGet: searchVersesCollectionGet,
    },
    verseOfTheDays: {
      queryFilters: () => resourceQueryFilters(cacheScope, "verseOfTheDays"),
      canonicalCollectionGet: verseOfTheDaysCanonicalCollectionGet,
      canonicalResourceGet: verseOfTheDaysCanonicalResourceGet,
    },
  };
}
