# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        V1OrganizationsBiblesCollectionGetRequestPageSize,
        V1OrganizationsBiblesCollectionGetResponse,
        V1OrganizationsBiblesCollectionGetResponseDataItem,
        V1OrganizationsCollectionGetRequestPageSize,
        V1OrganizationsCollectionGetResponse,
        V1OrganizationsCollectionGetResponseDataItem,
        V1OrganizationsCollectionGetResponseDataItemAddress,
        V1OrganizationsCollectionGetResponseDataItemAddressAdministrativeAreaLevel1,
        V1OrganizationsCollectionGetResponseDataItemAddressCountry,
        V1OrganizationsCollectionGetResponseDataItemAddressLocality,
        V1OrganizationsResourceGetResponse,
        V1OrganizationsResourceGetResponseAddress,
        V1OrganizationsResourceGetResponseAddressAdministrativeAreaLevel1,
        V1OrganizationsResourceGetResponseAddressCountry,
        V1OrganizationsResourceGetResponseAddressLocality,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "V1OrganizationsBiblesCollectionGetRequestPageSize": ".types",
    "V1OrganizationsBiblesCollectionGetResponse": ".types",
    "V1OrganizationsBiblesCollectionGetResponseDataItem": ".types",
    "V1OrganizationsCollectionGetRequestPageSize": ".types",
    "V1OrganizationsCollectionGetResponse": ".types",
    "V1OrganizationsCollectionGetResponseDataItem": ".types",
    "V1OrganizationsCollectionGetResponseDataItemAddress": ".types",
    "V1OrganizationsCollectionGetResponseDataItemAddressAdministrativeAreaLevel1": ".types",
    "V1OrganizationsCollectionGetResponseDataItemAddressCountry": ".types",
    "V1OrganizationsCollectionGetResponseDataItemAddressLocality": ".types",
    "V1OrganizationsResourceGetResponse": ".types",
    "V1OrganizationsResourceGetResponseAddress": ".types",
    "V1OrganizationsResourceGetResponseAddressAdministrativeAreaLevel1": ".types",
    "V1OrganizationsResourceGetResponseAddressCountry": ".types",
    "V1OrganizationsResourceGetResponseAddressLocality": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "V1OrganizationsBiblesCollectionGetRequestPageSize",
    "V1OrganizationsBiblesCollectionGetResponse",
    "V1OrganizationsBiblesCollectionGetResponseDataItem",
    "V1OrganizationsCollectionGetRequestPageSize",
    "V1OrganizationsCollectionGetResponse",
    "V1OrganizationsCollectionGetResponseDataItem",
    "V1OrganizationsCollectionGetResponseDataItemAddress",
    "V1OrganizationsCollectionGetResponseDataItemAddressAdministrativeAreaLevel1",
    "V1OrganizationsCollectionGetResponseDataItemAddressCountry",
    "V1OrganizationsCollectionGetResponseDataItemAddressLocality",
    "V1OrganizationsResourceGetResponse",
    "V1OrganizationsResourceGetResponseAddress",
    "V1OrganizationsResourceGetResponseAddressAdministrativeAreaLevel1",
    "V1OrganizationsResourceGetResponseAddressCountry",
    "V1OrganizationsResourceGetResponseAddressLocality",
]
