# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v1search_verses_collection_get_response_verses_item import V1SearchVersesCollectionGetResponseVersesItem


class V1SearchVersesCollectionGetResponse(UniversalBaseModel):
    """
    A paginated list of Bible verse search results. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint.
    """

    verses: typing.Optional[typing.List[V1SearchVersesCollectionGetResponseVersesItem]] = None
    user_intent: typing.Optional[str] = pydantic.Field(default=None)
    """
    The intent the Core Search service resolved for the query.
    """

    did_you_mean: typing.List[str] = pydantic.Field()
    """
    Alternative spellings the search service suggests for the query.
    """

    search_instead_for: typing.Optional[str] = pydantic.Field(default=None)
    """
    A corrected query the results were actually returned for, if any.
    """

    next_page_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token to send to the server when retrieving the next page of results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
