# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1search_queries_collection_get_response import V1SearchQueriesCollectionGetResponse
from pydantic import ValidationError


class RawSearchQueriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1search_queries_collection_get(
        self,
        *,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        query: typing.Optional[str] = None,
        trending: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Optional[V1SearchQueriesCollectionGetResponse]]:
        """
        Returns query objects (a search string and its source). Supply query with language_ranges[] for as-you-type suggestions, or trending=true with language_ranges[] for recently popular searches. When trending=true, query is ignored. The first language range supported by search is used.

        Parameters
        ----------
        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        query : typing.Optional[str]
            The partial query for as-you-type suggestions. Omit for trending queries.

        trending : typing.Optional[bool]
            Return recently popular searches for the language instead of suggestions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[V1SearchQueriesCollectionGetResponse]]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/search-queries",
            method="GET",
            params={
                "language_ranges[]": language_ranges,
                "query": query,
                "trending": trending,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1SearchQueriesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1SearchQueriesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSearchQueriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1search_queries_collection_get(
        self,
        *,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        query: typing.Optional[str] = None,
        trending: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Optional[V1SearchQueriesCollectionGetResponse]]:
        """
        Returns query objects (a search string and its source). Supply query with language_ranges[] for as-you-type suggestions, or trending=true with language_ranges[] for recently popular searches. When trending=true, query is ignored. The first language range supported by search is used.

        Parameters
        ----------
        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        query : typing.Optional[str]
            The partial query for as-you-type suggestions. Omit for trending queries.

        trending : typing.Optional[bool]
            Return recently popular searches for the language instead of suggestions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[V1SearchQueriesCollectionGetResponse]]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/search-queries",
            method="GET",
            params={
                "language_ranges[]": language_ranges,
                "query": query,
                "trending": trending,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300 and not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[V1SearchQueriesCollectionGetResponse],
                    parse_obj_as(
                        type_=typing.Optional[V1SearchQueriesCollectionGetResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
