# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1search_unified_collection_get_request_user_intent import V1SearchUnifiedCollectionGetRequestUserIntent
from .types.v1search_unified_collection_get_response import V1SearchUnifiedCollectionGetResponse
from pydantic import ValidationError


class RawSearchUnifiedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1search_unified_collection_get(
        self,
        *,
        query: str,
        bible_id: int,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        user_intent: typing.Optional[V1SearchUnifiedCollectionGetRequestUserIntent] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[V1SearchUnifiedCollectionGetResponse]:
        """
        Search for Bible verses and related topics by query, returning a single unified set of results across all content kinds. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint.

        This endpoint is unpaginated: it returns one combined page of top results per kind and exposes no page_size or page_token parameters. Use the kind-specific endpoints (search-verses, search-topics) when you need to page through the full result set for a single kind.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        bible_id : int
            The Bible version identifier

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        user_intent : typing.Optional[V1SearchUnifiedCollectionGetRequestUserIntent]
            The searcher's intent. Defaults to unknown, matching the Core Search service.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Result kinds to include: `verses` and/or `topics`. Use bracket notation to pass multiple
            values, for example `fields[]=verses&fields[]=topics`. Omit to return all kinds. Query
            metadata is always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1SearchUnifiedCollectionGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/search-unified",
            method="GET",
            params={
                "query": query,
                "bible_id": bible_id,
                "language_ranges[]": language_ranges,
                "user_intent": user_intent,
                "fields[]": fields,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1SearchUnifiedCollectionGetResponse,
                    parse_obj_as(
                        type_=V1SearchUnifiedCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSearchUnifiedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1search_unified_collection_get(
        self,
        *,
        query: str,
        bible_id: int,
        language_ranges: typing.Union[str, typing.Sequence[str]],
        user_intent: typing.Optional[V1SearchUnifiedCollectionGetRequestUserIntent] = None,
        fields: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[V1SearchUnifiedCollectionGetResponse]:
        """
        Search for Bible verses and related topics by query, returning a single unified set of results across all content kinds. Verse results carry references and metadata only (e.g. JHN.3.16), never passage text; resolve verse text through the licensed-content endpoint.

        This endpoint is unpaginated: it returns one combined page of top results per kind and exposes no page_size or page_token parameters. Use the kind-specific endpoints (search-verses, search-topics) when you need to page through the full result set for a single kind.

        Parameters
        ----------
        query : str
            The search query string used to find matching results.

        bible_id : int
            The Bible version identifier

        language_ranges : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            An ordered list of language ranges using bracket notation. Use repeated parameters like `language_ranges[]=en&language_ranges[]=es` to supply multiple ranges, and use the wildcard * to match all languages. A language range is much like a language tag but may contain wildcards.  See RFC 4647 section 2 for the full definition: https://www.rfc-editor.org/rfc/rfc4647.html#section-2
            Language ranges in this parameter may only be of the Basic Range format.

        user_intent : typing.Optional[V1SearchUnifiedCollectionGetRequestUserIntent]
            The searcher's intent. Defaults to unknown, matching the Core Search service.

        fields : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Result kinds to include: `verses` and/or `topics`. Use bracket notation to pass multiple
            values, for example `fields[]=verses&fields[]=topics`. Omit to return all kinds. Query
            metadata is always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1SearchUnifiedCollectionGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/search-unified",
            method="GET",
            params={
                "query": query,
                "bible_id": bible_id,
                "language_ranges[]": language_ranges,
                "user_intent": user_intent,
                "fields[]": fields,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1SearchUnifiedCollectionGetResponse,
                    parse_obj_as(
                        type_=V1SearchUnifiedCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
