// Code generated by Fern. DO NOT EDIT.

package fonts

import (
	context "context"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get a collection of font family resources with their available variants and CDN sources.
func (c *Client) V1FontsCollectionGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (*platform.V1FontsCollectionGetResponse, error) {
	response, err := c.WithRawResponse.V1FontsCollectionGet(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a single font family resource by its integer identifier.
func (c *Client) V1FontsResourceGet(
	ctx context.Context,
	request *platform.V1FontsResourceGetRequest,
	opts ...option.RequestOption,
) (*platform.V1FontsResourceGetResponse, error) {
	response, err := c.WithRawResponse.V1FontsResourceGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a text/css stylesheet for a single font family resource using the canonical woff2 CDN URLs exposed by the JSON Fonts API for browser consumption. The API gateway accepts `app_key` on this route and injects the required app-id header before forwarding the request to this service.
func (c *Client) V1FontsStylesheetGet(
	ctx context.Context,
	request *platform.V1FontsStylesheetGetRequest,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.V1FontsStylesheetGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}
