// Code generated by Fern. DO NOT EDIT.

// Provides metadata for font families approved for Platform consumers. Use these endpoints to
// discover available families, variants, and CDN asset URLs.
package fonts
