// Code generated by Fern. DO NOT EDIT.

package fonts

import (
	bytes "bytes"
	context "context"
	http "net/http"
	url "net/url"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) V1FontsCollectionGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*platform.V1FontsCollectionGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := baseURL + "/v1/fonts"
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	var response *platform.V1FontsCollectionGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*platform.V1FontsCollectionGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) V1FontsResourceGet(
	ctx context.Context,
	request *platform.V1FontsResourceGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*platform.V1FontsResourceGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/fonts/%v",
		request.FontID,
	)
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	var response *platform.V1FontsResourceGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*platform.V1FontsResourceGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) V1FontsStylesheetGet(
	ctx context.Context,
	request *platform.V1FontsStylesheetGetRequest,
	opts ...option.RequestOption,
) (*core.Response[string], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.youversion.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/fonts/%v/stylesheet",
		request.FontID,
	)
	headers, err := r.options.ToHeader(options, true)
	if err != nil {
		return nil, err
	}
	query := make(url.Values)
	for name, values := range options.QueryParameters {
		query[name] = append([]string(nil), values...)
	}
	appKey := r.options.YvpAppKey
	if options.YvpAppKey != "" {
		appKey = options.YvpAppKey
	}
	query.Set("app_key", appKey)
	options.QueryParameters = query
	response := bytes.NewBuffer(nil)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[string]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response.String(),
	}, nil
}
