# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bibles_books_resource_get_response_chapters_item_verses_item import (
    BiblesBooksResourceGetResponseChaptersItemVersesItem,
)


class BiblesBooksResourceGetResponseChaptersItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chapter identifier
    """

    passage_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Passage identifier
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chapter title
    """

    verses: typing.Optional[typing.List[BiblesBooksResourceGetResponseChaptersItemVersesItem]] = pydantic.Field(
        default=None
    )
    """
    Verses in the chapter
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
