# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bibles_books_collection_get_response_data_item_canon import BiblesBooksCollectionGetResponseDataItemCanon
from .bibles_books_collection_get_response_data_item_chapters_item import (
    BiblesBooksCollectionGetResponseDataItemChaptersItem,
)
from .bibles_books_collection_get_response_data_item_intro import BiblesBooksCollectionGetResponseDataItemIntro


class BiblesBooksCollectionGetResponseDataItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book identifier
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book title
    """

    full_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full book title if available
    """

    abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Book name abbreviation if provided by the publisher
    """

    canon: typing.Optional[BiblesBooksCollectionGetResponseDataItemCanon] = pydantic.Field(default=None)
    """
    Canon identifier
    """

    chapters: typing.Optional[typing.List[BiblesBooksCollectionGetResponseDataItemChaptersItem]] = pydantic.Field(
        default=None
    )
    """
    Chapters in the book
    """

    intro: typing.Optional[BiblesBooksCollectionGetResponseDataItemIntro] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
