# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPermissionsClient, RawPermissionsClient
from .types.v1apps_permissions_collection_get_response import V1AppsPermissionsCollectionGetResponse


class PermissionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPermissionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPermissionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPermissionsClient
        """
        return self._raw_client

    def v1apps_permissions_collection_get(
        self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V1AppsPermissionsCollectionGetResponse:
        """
        Returns permissions the authenticated user has already granted to the calling app. Use this
        endpoint before starting an OAuth permission request when you need to know whether the user
        has already granted access. The app ID path parameter must match the gateway-injected
        calling app ID. An empty permissions array means the user has not granted permissions for
        this app.

        Parameters
        ----------
        app_id : str
            The unique identifier of the app.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1AppsPermissionsCollectionGetResponse
            Successful request

        Examples
        --------
        from cameronapak_platform_sdk import PlatformClient

        client = PlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )
        client.permissions.v1apps_permissions_collection_get(
            app_id="app_id",
        )
        """
        _response = self._raw_client.v1apps_permissions_collection_get(app_id, request_options=request_options)
        return _response.data


class AsyncPermissionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPermissionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPermissionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPermissionsClient
        """
        return self._raw_client

    async def v1apps_permissions_collection_get(
        self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V1AppsPermissionsCollectionGetResponse:
        """
        Returns permissions the authenticated user has already granted to the calling app. Use this
        endpoint before starting an OAuth permission request when you need to know whether the user
        has already granted access. The app ID path parameter must match the gateway-injected
        calling app ID. An empty permissions array means the user has not granted permissions for
        this app.

        Parameters
        ----------
        app_id : str
            The unique identifier of the app.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V1AppsPermissionsCollectionGetResponse
            Successful request

        Examples
        --------
        import asyncio

        from cameronapak_platform_sdk import AsyncPlatformClient

        client = AsyncPlatformClient(
            yvp_app_key="YOUR_YVP_APP_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.v1apps_permissions_collection_get(
                app_id="app_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.v1apps_permissions_collection_get(app_id, request_options=request_options)
        return _response.data
