# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.v1apps_permissions_collection_get_response import V1AppsPermissionsCollectionGetResponse
from pydantic import ValidationError


class RawPermissionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def v1apps_permissions_collection_get(
        self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[V1AppsPermissionsCollectionGetResponse]:
        """
        Returns permissions the authenticated user has already granted to the calling app. Use this
        endpoint before starting an OAuth permission request when you need to know whether the user
        has already granted access. The app ID path parameter must match the gateway-injected
        calling app ID. An empty permissions array means the user has not granted permissions for
        this app.

        Parameters
        ----------
        app_id : str
            The unique identifier of the app.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[V1AppsPermissionsCollectionGetResponse]
            Successful request
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/apps/{encode_path_param(app_id)}/permissions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1AppsPermissionsCollectionGetResponse,
                    parse_obj_as(
                        type_=V1AppsPermissionsCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPermissionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def v1apps_permissions_collection_get(
        self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[V1AppsPermissionsCollectionGetResponse]:
        """
        Returns permissions the authenticated user has already granted to the calling app. Use this
        endpoint before starting an OAuth permission request when you need to know whether the user
        has already granted access. The app ID path parameter must match the gateway-injected
        calling app ID. An empty permissions array means the user has not granted permissions for
        this app.

        Parameters
        ----------
        app_id : str
            The unique identifier of the app.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[V1AppsPermissionsCollectionGetResponse]
            Successful request
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/apps/{encode_path_param(app_id)}/permissions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    V1AppsPermissionsCollectionGetResponse,
                    parse_obj_as(
                        type_=V1AppsPermissionsCollectionGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
