// Code generated by Fern. DO NOT EDIT.

package organizations

import (
	context "context"

	platform "github.com/cameronapak/Platform-SDK-TS/packages/go"
	core "github.com/cameronapak/Platform-SDK-TS/packages/go/core"
	internal "github.com/cameronapak/Platform-SDK-TS/packages/go/internal"
	option "github.com/cameronapak/Platform-SDK-TS/packages/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a paginated list of Organization objects. Use bible_ids[] to filter
// to organizations associated with the given Bible version(s); when omitted,
// all organizations are returned.
func (c *Client) V1OrganizationsCollectionGet(
	ctx context.Context,
	request *platform.V1OrganizationsCollectionGetRequest,
	opts ...option.RequestOption,
) (*platform.V1OrganizationsCollectionGetResponse, error) {
	response, err := c.WithRawResponse.V1OrganizationsCollectionGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a single organization resource by its id.
func (c *Client) V1OrganizationsResourceGet(
	ctx context.Context,
	request *platform.V1OrganizationsResourceGetRequest,
	opts ...option.RequestOption,
) (*platform.V1OrganizationsResourceGetResponse, error) {
	response, err := c.WithRawResponse.V1OrganizationsResourceGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get bibles associated with a specific organization by its id.
func (c *Client) V1OrganizationsBiblesCollectionGet(
	ctx context.Context,
	request *platform.V1OrganizationsBiblesCollectionGetRequest,
	opts ...option.RequestOption,
) (*platform.V1OrganizationsBiblesCollectionGetResponse, error) {
	response, err := c.WithRawResponse.V1OrganizationsBiblesCollectionGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
