// Code generated by Fern. DO NOT EDIT.

// Provides information about our publishing partners in the YouVersion platform.  Use these to get
// information about the organizations which provide Bible versions.
package organizations
